var scrollTopFlag=false;var scrollBottomFlag=false;var scrollBottomCounter=0;var lastScrollTop=0;var isEdge=!isIE&&!!window.StyleMedia;var isIE=false||!!document.documentMode;var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==="[object SafariRemoteNotification]";})(!window['safari']||(typeof safari!=='undefined'&&safari.pushNotification));var iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;var isAnimationBackward=false,isAnimationForward=false;var aboveSection=null;var aboutHighlightTextColor="#1CA6DF";var isMobile=false,isDesktop=false;if(isIE||isEdge){$('body').addClass('edge-browser');}
if(iOS){$('body').addClass('ios-browser');}
$(document).ready(function(){if($(".should-stickey").length){if($(window).scrollTop()>0){$('.site-header').addClass('scrolled');}else{$('.site-header').removeClass('scrolled');}}
setTimeout(function(){if($(".no-fullpage").length){$(".no-fullpage").animate({opacity:1},20);}},1000);esgTab();});$(window).scroll(function(e){if($(".should-stickey").length){if($(window).scrollTop()>0){$('.site-header').addClass('scrolled');}
else if(!$('.more-menu-link').hasClass('open')){$('.site-header').removeClass('scrolled');}}});$(window).resize(function(){if(window.matchMedia("(min-width: 992px)").matches){moremenuSidebarBgPlacement();}
setVideoHeight();splitLinesAnimation(".intro-section-txt",true);});window.onresize=function(event){esgApproachSliderButtonHeight();esgTab();console.log("windows resize");};const options=[{from:'(.*)',to:'(.*)',in:function(next){if(isAnimationUp){animateTopSlantIn(next);}
else{animateSlantIn(next);}},out:function(next){if(isAnimationUp){animateTopSlantOut(next);isAnimationUp=false;}
else if(isAnimationBackward||isAnimationForward){animateFadeOutLeft(next);isAnimationBackward=isAnimationForward=false;}
else{animateSlantOut(next);}}},{from:'(.*)',to:'more-menu.html',in:function(next){animateMenuIn(next);},out:function(next){animateMenuOut(next);}},{from:'(.*)',to:'detail-page-transition',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/news/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/portfolio/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/people/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/case-studies/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/esgandimpact/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}}];const swup=new Swup({animateHistoryBrowsing:true,plugins:[new SwupScrollPlugin(),new SwupJsPlugin(options),new SwupScriptsPlugin(),new SwupBodyClassPlugin(),new SwupPreloadPlugin()]});init();swup.on('contentReplaced',init);swup.on('willReplaceContent',unload);swup.on('clickLink',changePageSlantColor);swup.on('popState',changePageSlantColor);if($('.scroll-up-sec').length){var scrollUpSecOffsetTop=$('.scroll-up-sec').offset().top;var scrollUpSecHeight=$('.scroll-up-sec').outerHeight();var scrollUpSecOffsetBottom=scrollUpSecOffsetTop+scrollUpSecHeight;}
swup.on('contentReplaced',function(){if($(".no-fullpage").length){swup.scrollTo(scrollUpSecOffsetBottom);}});if($(".no-fullpage").length){swup.scrollTo(scrollUpSecOffsetBottom);}
swup.on('transitionEnd',function(){scrollTopFlag=false;setTimeout(function(){if($(".no-fullpage").length){$(".no-fullpage").animate({opacity:1},20);}},1000);});swup.on('scrollDone',function(){setTimeout(function(){if($(".no-fullpage").length){$(".no-fullpage").animate({opacity:1},20);}},1000);});swup.on('animationInStart',function(){pageScrollDetect();});swup.on('animationOutStart',function(){pageScrollDetect();});swup.on('popState',function(event){var fromPage=sessionStorage.getItem('thisPage');var toPage=getPageNameFromPath(event.target.location.pathname);isAnimationBackward=(fromPage.startsWith("/news/*")&&toPage.startsWith("/news"))||(fromPage.startsWith("/portfolio/*")&&toPage.startsWith("/portfolio"))||(fromPage.startsWith("/people/*")&&toPage.startsWith("/people"));(fromPage.startsWith("/esgandimpact/*")&&toPage.startsWith("/esgandimpact"));(fromPage.startsWith("/case-studies/*")&&toPage.startsWith("/strategy"));isAnimationForward=(fromPage.startsWith("/news")&&toPage.startsWith("/news/*"))||(fromPage.startsWith("/portfolio")&&toPage.startsWith("/portfolio/*"))||(fromPage.startsWith("/people")&&toPage.startsWith("/people/*"));(fromPage.startsWith("/esgandimpact")&&toPage.startsWith("/esgandimpact/*"));(fromPage.startsWith("/strategy")&&toPage.startsWith("/case-studies/*"));});swup.on('pageView',function(){setLocation();setMenuActive();setVideoHeight();});document.addEventListener("DOMContentLoaded",function(event){setLocation();setMenuActive();setVideoHeight();});function pageScrollDetect(){var currentPage=document.location.pathname.match(/[^\/]+$/);var pageNextLink,pagePrevLink;if(currentPage=='our-approach.html'){pagePrevLink='index.html'}else{pagePrevLink=$(".bottom-header .navbar-nav > li.active a").parent().prev().children("a").attr("href");}
if(currentPage=='index.html'){pageNextLink='our-approach.html'}
else{pageNextLink=$(".bottom-header .navbar-nav > li.active a").parent().next().children("a").attr("href");}
isAnimationUp=$('body').hasClass('fp-viewing-page2');}
function setLocation(){var urlPath=window.location.pathname;var thisPage=getPageNameFromPath(urlPath);var lastPage=sessionStorage.getItem('thisPage');sessionStorage.setItem('thisPage',thisPage);sessionStorage.setItem('lastPage',lastPage);}
function getPageNameFromPath(url){var urlArr=url.split('/');var pageName="index";if(urlArr[urlArr.length-1].length){pageName=urlArr[urlArr.length-1];}
return pageName;}
function setMenuActive(){if(sessionStorage.getItem('thisPage')=="more-menu"){$('.about-menu li a').removeClass('active')
$('.about-menu li').each(function(){var $anc=$(this).find('a');var href=$anc.attr('href');var pageName=getPageNameFromPath(href);var lastPage=sessionStorage.getItem('lastPage');if(pageName==lastPage){$anc.addClass('active');}});}}
function animateFadeIn(next){const tlFadeIn=gsap.timeline({paused:true});tlFadeIn.fromTo('.site-content-cover',0.6,{autoAlpha:0},{autoAlpha:1,ease:Linear.easeOut,onComplete:next},0).play();}
function animateFadeOutLeft(next){const tlFadeOutLeft=gsap.timeline({paused:true});tlFadeOutLeft.to('.site-content-cover',0.6,{xPercent:-100,autoAlpha:0,ease:Linear.easeOut,onComplete:next},0).play();}
function animateTopSlantIn(next){const tlSlantIn=gsap.timeline({paused:true});tlSlantIn.to('.page-slants-top',0.2,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants-top .left-slant',0.2,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants-top .right-slant',0.2,{autoAlpha:0,ease:Linear.easeOut,},0).to('.page-slants-top .left-slant',0,{y:'0vh',ease:Linear.easeIn},1).to('.page-slants-top .right-slant',0,{y:'0vh',ease:Linear.easeIn,onComplete:next},1).play();}
function animateTopSlantOut(next){const tlSlantOut=gsap.timeline({paused:true});tlSlantOut.to('.page-slants-top',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.page-slants-top .left-slant',0,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants-top .right-slant',0,{autoAlpha:1,ease:Linear.easeOut,},0).to('.page-slants-top .left-slant',0.6,{y:0,ease:Linear.easeIn},0).to('.page-slants-top .right-slant',0.6,{y:'180vh',ease:Linear.easeIn,onComplete:next},0).play();}
function animateSlantIn(next){const tlSlantIn=gsap.timeline({paused:true});tlSlantIn.to('.page-slants',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants .left-slant',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants .right-slant',0.4,{autoAlpha:0,ease:Linear.easeOut,},0).to('.page-slants .left-slant',0,{yPercent:0,ease:Linear.easeIn},1).to('.page-slants .right-slant',0,{yPercent:0,ease:Linear.easeIn,onComplete:next},1).play();}
function animateSlantOut(next){const tlSlantOut=gsap.timeline({paused:true});tlSlantOut.to('.page-slants',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.page-slants .left-slant',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.page-slants .right-slant',0,{autoAlpha:1,ease:Linear.easeOut,},0).to('.page-slants .left-slant',1,{yPercent:-80,ease:Linear.easeIn},0).to('.page-slants .right-slant',1,{yPercent:-80,ease:Linear.easeIn,onComplete:next},0).play();}
function animateMenuIn(next){const tlMenuIn=gsap.timeline({paused:true});tlMenuIn.to('.more-menu-slants',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.more-menu-slants .left-slant',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.more-menu-slants .right-slant',0.4,{autoAlpha:0,ease:Linear.easeOut,},0).to('.more-menu-slants .left-slant',0,{left:'-100%',ease:Linear.easeIn},0.4).to('.more-menu-slants .right-slant',0,{left:'100%',ease:Linear.easeIn,onComplete:next},0.4).play();}
function animateMenuOut(next){const tlMenuOut=gsap.timeline({paused:true});tlMenuOut.to('.more-menu-slants',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.more-menu-slants .left-slant',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.more-menu-slants .right-slant',0,{autoAlpha:1,ease:Linear.easeOut,},0).to('.more-menu-slants .left-slant',0.4,{left:'-10%',ease:Linear.easeIn},0).to('.more-menu-slants .right-slant',0.4,{left:'-10%',ease:Linear.easeIn,onComplete:next},0).play();}
function changePageSlantColor(){if($('.page-slants').length){var leftPageSlant,rightPageSlant;if($('.page-slants > .left-slant').length){leftPageSlant=$('.page-slants > .left-slant');}
if($('.page-slants > .right-slant').length){rightPageSlant=$('.page-slants > .right-slant');}
if($('.page-slants-top > .left-slant').length){leftPageTopSlant=$('.page-slants-top > .left-slant');}
if($('.page-slants-top > .right-slant').length){rightPageTopSlant=$('.page-slants-top > .right-slant');}
setTimeout(function(){var targetLinkHrefLocation=document.location.pathname.match(/[^\/]+$/);if(targetLinkHrefLocation&&targetLinkHrefLocation.length){var targetLinkHref=(targetLinkHrefLocation[0]);console.log(targetLinkHref);if(targetLinkHref=="active-governance-and-stewardship.html"){$(leftPageSlant).css('background-color','#0047bb');$(leftPageTopSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#e6e6e3');$(rightPageTopSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="sustainable-growth-reducing-climate-impact.html"){$(leftPageSlant).css('background-color','#0047bb');$(leftPageTopSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#e6e6e3');$(rightPageTopSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="fair-employment-engagement-well-being.html"){$(leftPageSlant).css('background-color','#0047bb');$(leftPageTopSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#e6e6e3');$(rightPageTopSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="active-governance-and-stewardship.html"){$(leftPageSlant).css('background-color','#0047bb');$(leftPageTopSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#e6e6e3');$(rightPageTopSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="community-engagement.html"){$(leftPageSlant).css('background-color','#0047bb');$(leftPageTopSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#e6e6e3');$(rightPageTopSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else{$(leftPageSlant).css('background-color','#1e3278');$(leftPageTopSlant).css('background-color','#1e3278');$(rightPageSlant).css('background-color','#1C2156');$(rightPageTopSlant).css('background-color','#1C2156');$('body').css('background-color','#1C2156');}}},10);}}
function init(){updateHeight();caseStudyGrid();$(window).resize(function(){updateHeight();caseStudyGrid();});$(window).resize(updateHeight);fpGenerate();var $mapSvgWrap=$('.map-svg-wrap');var $mapSvgMobileWrap=$('.map-svg-mobile-wrap');if($mapSvgWrap.length){am4core.useTheme(am4themes_animated);var chart=am4core.create("chartdiv",am4maps.MapChart);chart.maxZoomLevel=100;chart.chartContainer.wheelable=false;if(window.matchMedia("(min-width: 768px)").matches){chart.seriesContainer.events.disableType("doublehit");}
chart.geodata=am4geodata_worldLow;chart.projection=new am4maps.projections.Miller();var polygonSeries=chart.series.push(new am4maps.MapPolygonSeries());polygonSeries.exclude=["AQ"];polygonSeries.useGeodata=true;var polygonTemplate=polygonSeries.mapPolygons.template;polygonTemplate.polygon.fillOpacity=1;polygonTemplate.fill=am4core.color("#1C2156");polygonTemplate.stroke=am4core.color("#1E3278");var imageSeries=chart.series.push(new am4maps.MapImageSeries());imageSeries.fill=am4core.color("#1C2156");imageSeries.strokeOpacity=0;imageSeries.fillOpacity=1;var imageTemplate=imageSeries.mapImages.template;imageTemplate.propertyFields.longitude="longitude";imageTemplate.propertyFields.latitude="latitude";var label=imageTemplate.createChild(am4core.Label);label.align="left";label.verticalCenter="middle";label.pointerOrientation="down";label.fill=am4core.color("#ffffff");label.nonScaling=true;label.fontSize="26px";label.fontFamily="fs_silas_sans";label.fontWeight="400";imageSeries.tooltip.getFillFromObject=false;imageSeries.tooltip.background.propertyFields.fill="color";imageSeries.tooltip.background.fill=am4core.color("#ffffff");imageSeries.tooltip.background.fillOpacity=1;imageSeries.tooltip.background.cornerRadius=15;imageSeries.tooltip.keepTargetHover=true;imageSeries.tooltip.label.interactionsEnabled=true;imageSeries.tooltip.pointerOrientation="horizontal";imageSeries.tooltip.label.maxWidth=400;imageSeries.tooltip.label.wrap=true;imageSeries.tooltip.fontSize=16;imageSeries.tooltip.fontFamily="fs_silas_sans";imageSeries.tooltip.zIndex="99999";imageSeries.tooltip.dy=-5;imageSeries.tooltip.dx=-5;imageTemplate.cursorOverStyle=am4core.MouseCursorStyle.pointer;var mapMarker;imageTemplate.tooltipHTML="";imageTemplate.alwaysShowTooltip=true;imageTemplate.events.on("hit",function(ev){var address={address};var phone_number={phone_number};var fax_number={fax_number};if(mapMarker){mapMarker.tooltip.hide();}
mapMarker=ev.target;mapMarker.tooltipHTML='<div class="amchart-content"><a class="address-popup-close" style="visibility: visible;"></a><div class="ampopup-inside"><div class="map-address">{address}</div></div></div>';mapMarker.invalidate();ev.target.tooltip.zIndex=999999;$('.contact-section').addClass('tooltip-open');mapMarker.showTooltip();});am4core.getInteraction().body.events.on("hit",function(ev){if(mapMarker){mapMarker.tooltip.hide();}});let imageSeriesTemplate=imageSeries.mapImages.template;let marker=imageSeriesTemplate.createChild(am4core.Image);marker.href="images/map-marker.svg";marker.width=15;marker.height=15;$(document).click(function(e){if(!$(e.target).is('svg image')){chart.closeAllPopups();}});if(window.matchMedia("(max-width: 991px)").matches){chart.chartContainer.wheelable=true;marker.width=10;marker.height=10;}
marker.nonScaling=true;marker.horizontalCenter="middle";marker.verticalCenter="bottom";imageSeries.data=[{"latitude":42.361145,"longitude":-71.057083,"address":"200 Clarendon Street <br/>Boston, MA 02116 <br/>United States <br/>Main: <a href='tel:+16175162000'>+1 (617) 516-2000</a> <br/>Fax: <a href='fax:+16175162000'>+1 (617) 516-2010</a>",},{"latitude":37.4478028,"longitude":-122.1593862,"address":"524 Hamilton Avenue <br/> Palo Alto, CA 94301 <br/> United States <br/>Main: <a href='tel:+16507982500'>+1 (650) 798-2500</a>",}];}
$(document).click('.page-search-field',function(){$('#investmentsSearch').focus();});if($('.video-wrap').length){$('.video-wrap').each(function(){const player=new Plyr($(this).find('.video-frame'));$(this).find('.videoPlayLink').on('click',function(){$(this).parent().find('.img-fluid').hide();$(this).parent().find('.video-caption').hide();$(this).hide();player.play();});});}
var isIE=false||!!document.documentMode;var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==="[object SafariRemoteNotification]";})(!window['safari']||(typeof safari!=='undefined'&&safari.pushNotification));var iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;if(isIE||isEdge){$('body').addClass('edge-browser');}
if(iOS){$('body').addClass('ios-browser');}
changePageSlantColor();if(window.matchMedia("(min-width: 992px)").matches){moremenuSidebarBgPlacement();}
$(".more-menu-sidebar .search-widget #keys").focus(function(){$('.more-menu-sidebar .typedtext').hide();$('.more-menu-sidebar .underscore').hide();});$('.more-menu-sidebar .search-widget #keys').blur(function(){if(!$(this).val()){$('.more-menu-sidebar .typedtext').show();$('.more-menu-sidebar .underscore').show();}});var revealDuration=1;var revealStartTime=0.5;if($(".video-banner-caption").length){var videoCaption=gsap.timeline();videoCaption.to('.video-banner-caption-text',revealDuration,{autoAlpha:1},revealStartTime).pause();videoCaption.play();}
if($(".intro-section-slants").length){var introSlant=gsap.timeline({paused:true});if($('.intro-section-slants .left-slant').length){introSlant.to('.intro-section-slants .left-slant',9,{yPercent:-100});}
if($('.intro-section-slants .right-slant').length){introSlant.to('.intro-section-slants .right-slant',7,{yPercent:-100},0);}}
if($(".gradient-section-slants").length){var gradientSlant=gsap.timeline({paused:true});if($('.gradient-section-slants .left-slant').length){gradientSlant.to('.gradient-section-slants .left-slant',2,{yPercent:-15});}
if($('.gradient-section-slants .right-slant').length){gradientSlant.to('.gradient-section-slants .right-slant',2,{yPercent:-15},0);}}
if($(".sitemap-section").length){var sitemapAnim=gsap.timeline();sitemapAnim.fromTo('.sitemap-top-wrap, .sitemap-bottom-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},+1).pause();}
if($(".section-top-slant").length){var gradientTopSlant=gsap.timeline({paused:true});gradientTopSlant.fromTo('.section-top-slant',0.8,{yPercent:0},{yPercent:-100,ease:Linear.easeNone},"+=0.5");}
if($(".home-page-slants").length){var homeSlantHide=gsap.timeline({paused:true});homeSlantHide.fromTo('.home-page-slant-item',0.8,{yPercent:0},{yPercent:-1,ease:Linear.easeNone},"+=0.1");}
if($(".page-title, .section-title, .small-section-title").length){var pageTitleTL=gsap.timeline();pageTitleTL.fromTo('.page-title, .section-title, .small-section-title',revealDuration,{xPercent:0,autoAlpha:0},{xPercent:0,autoAlpha:1},revealStartTime).pause();pageTitleTL.play();}
sessionStorage.setItem("aboutHtml",$(".intro-section-txt").html());if($(".intro-section-txt").length){$('.intro-section-txt').splitLines({tag:'<div>',keepHtml:true});}
if($("[data-splitting]").length){Splitting();}
if($(".intro-section-txt").length){var introText=gsap.timeline({onComplete:function(){$(".intro-section-txt").addClass("animation-complete");}});introText.to('.intro-section-txt',0.1,{autoAlpha:1}).staggerFromTo('.intro-section-txt > div',0.3,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0,delay:0,ease:Power0.easeIn},0.1).to('.intro-section .read-more-link',0.35,{left:0,autoAlpha:1},"-=0.3").to('.intro-section .read-more-link i',0.2,{left:0,autoAlpha:1},"+=0.05").staggerTo('.highlighted-txt .char',0.02,{color:aboutHighlightTextColor,opacity:1,ease:Power1.easeIn},0.02,"+=1").pause();}
if($(".esg-landing-page-section").length){}
if($(".Strategy-section").length){var stretagySection=gsap.timeline();stretagySection.fromTo('.Strategy-section-wrap, .Strategy-intro',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime).pause();stretagySection.play();}
if($(".gradiant-counter-content-section").length){var gradiantCounter=gsap.timeline();gradiantCounter.fromTo('.gradiant-banner-title, .counter-column-wrapper, .gradient-section-slants-content-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},+1).pause();}
if($(".sitemap-section").length){var sitemapAnim=gsap.timeline();sitemapAnim.fromTo('.sitemap-top-wrap, .sitemap-bottom-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},+1).pause();}
if($(".approach-section-wrap").length){var strategySection=gsap.timeline();strategySection.fromTo('.approach-section-wrap .approach-intro-content',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($(".esg-block").length){var esgBlock=gsap.timeline({paused:true,onComplete:function(){$('.esg-block .esg-list').addClass('anime-completed')}});if($('.esg-block .esg-content').length){esgBlock.fromTo('.esg-block .esg-content',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.esg-block .esg-list').length){esgBlock.fromTo('.esg-block .esg-item',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime);}
var ctrlApproach=new ScrollMagic.Controller();var sceneEsgBlock=new ScrollMagic.Scene({triggerElement:".approach-section-wrap",reverse:false}).setTween(esgBlock.play()).addTo(ctrlApproach);if(window.matchMedia("(min-height: 768px)").matches){sceneEsgBlock.triggerHook(0.6);}else{sceneEsgBlock.triggerHook(0.5);}}
if($('.about-section').length){var aboutSection=gsap.timeline();aboutSection.fromTo('.about-sub-section, .about-spotlight-section, .year-review-section, .impact-themes-section, #approach, .about-section > .container, .about-section > .bg-slant',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime).pause();}
if($('.ip-slider').length){var ctrlIpSlider=new ScrollMagic.Controller();var tlIpSliderContent=gsap.timeline({paused:true});tlIpSliderContent.fromTo('.ip-header',0.5,{autoAlpha:0},{autoAlpha:1}).fromTo('.ip-slider .carousel-control',0.5,{autoAlpha:0},{autoAlpha:1});new ScrollMagic.Scene({triggerElement:".ip-slider",triggerHook:0.65,reverse:false}).setTween(tlIpSliderContent.play()).addTo(ctrlIpSlider);}
var tlIpSliderLoad=gsap.timeline({paused:true});var tlIpSliderChange;slides=$('.ip-slider .ip-item').toArray();var baseTime=0.12;var titleYPercent=115;function initIpSlider(){if($('.ip-slider').length){resetIpSlider();if(window.matchMedia("(min-width: 1200px)").matches){titleYPercent=115;}else{titleYPercent=140;}
var splitWidth=$('.ip-slider .ip-item.active .split-lines').outerWidth();if($(".ip-item-content").length){$('.investment-block .ip-item').each(function(index,item){$splitLine=$(item).find('.ip-item-content .split-lines');$heading=$(item).find('.ip-item-title .heading');$splitLine.attr('data-text',$splitLine.text());$heading.attr('data-text',$heading.text());$splitLine.splitLines({tag:'<div class="splitted"><span>',keepHtml:true,width:splitWidth});$heading.wrapInner('<span></span>');});}
$('.ip-slider .ip-item').addClass('carousel-item');tlIpSliderLoad.staggerFromTo('.ip-slider .ip-item.active .heading span, .ip-slider .ip-item.active .splitted span',baseTime*7.5,{autoAlpha:0,yPercent:titleYPercent},{autoAlpha:1,yPercent:0,ease:Power4.easeOut},baseTime);var sceneIpSlider=new ScrollMagic.Scene({triggerElement:".ip-slider",triggerHook:0.65,reverse:false}).setTween(tlIpSliderLoad.play()).addTo(ctrlIpSlider);tlIpSliderChange=new TimelineMax({paused:true});$(".ip-slider").on("slid.bs.carousel",function(event){handleIpSlideChange(event);});$('.ip-slider').carousel({pause:false,ride:true,interval:8000});$('.ip-slider').addClass('slider-initiated');setTimeout(function(){$('.ip-slider').removeClass('resizing');},800);}}
function resetIpSlider(){if($('.ip-slider').length){if($('.ip-slider').hasClass('slider-initiated')){$('.ip-slider').carousel('dispose').removeClass('slider-initiated');$('.ip-slider .ip-item').removeClass('carousel-item');tlIpSliderChange.kill();$('.investment-block .ip-item').each(function(index,item){$splitLine=$(item).find('.ip-item-content .split-lines');$splitLine.html($splitLine.attr('data-text'));$heading=$(item).find('.ip-item-title .heading');$heading.html($heading.attr('data-text'));});if(window.matchMedia("(min-width: 768px)").matches){titleYPercent=110;}else{titleYPercent=125;}}}}
initIpSlider();var loop;$(window).on('resize',function(){$('.ip-slider').addClass('resizing');clearTimeout(loop);loop=setTimeout(doneResizing,500);});function doneResizing(){initIpSlider();}
function handleIpSlideChange(event){var slideIndex=String(event.to+1).padStart(2,'0');$('.ip-slide-index').html(slideIndex);var baseTime=0.12;tlIpSliderChange.staggerFromTo($(slides[event.from]).find('.heading span'),baseTime*7.5,{yPercent:0},{yPercent:-titleYPercent,ease:Power4.easeOut},baseTime).addLabel("titleOutAnimeDone").staggerFromTo($(slides[event.from]).find('.splitted span'),baseTime*7.5,{autoAlpha:1,yPercent:0},{autoAlpha:0,yPercent:-100,ease:Power4.easeIn},baseTime,"titleOutAnimeDone-="+baseTime*10).addLabel("AllOutAnimeDone").staggerFromTo($(slides[event.to]).find('.splitted span'),baseTime*7.5,{autoAlpha:0,yPercent:100},{autoAlpha:1,yPercent:0,ease:Power4.easeOut},baseTime,"AllOutAnimeDone-="+baseTime*5).staggerFromTo($(slides[event.to]).find('.heading span'),baseTime*7.5,{yPercent:titleYPercent},{yPercent:0,ease:Power4.easeOut},baseTime,"AllOutAnimeDone-="+baseTime*4).play();}
if($(".guiding-principles-block").length){var guidingPronciplesSection=gsap.timeline({paused:true});if($('.guiding-principles-block .guiding-principles-note').length){guidingPronciplesSection.fromTo('.guiding-principles-block .guiding-principles-note',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime);}
if($('.guiding-principles-block .guiding-principles-icons-wrap .guiding-principles-icon-block').length){guidingPronciplesSection.fromTo('.guiding-principles-block .guiding-principles-icons-wrap .guiding-principles-icon-block',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime);}}
if($('.gradient-section-pin').length){var controller=new ScrollMagic.Controller();new ScrollMagic.Scene({triggerElement:".gradient-section-slants-content",triggerHook:1,}).setPin(".gradient-section-pin").addTo(controller);}
if($('.gradient-section-slants-content-wrap').length){var gredientSection=gsap.timeline({paused:true});gredientSection.fromTo('.gradient-section-slants-content-wrap .container img, .gradient-section-slants-content-wrap h3, .gradient-section-slants-content-wrap h2, .gradient-section-slants-content-wrap a, .gradient-section-slants-content-wrap .qsource',revealDuration,{autoAlpha:0},{autoAlpha:1},"+=1");}
if($(".portfolio-listing-section-wrap").length){var portfolioSection=gsap.timeline({paused:false});if($('.portfolio-caption, .portfolio-search').length){portfolioSection.fromTo('.portfolio-caption, .portfolio-search',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.portfolio-grid .grid-item').length){portfolioSection.fromTo('.portfolio-grid .grid-item',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".people-listing-section .portfolio-listing-section-wrap").length){var peopleSection=gsap.timeline({paused:false});if($('.people-listing .staff').length){peopleSection.fromTo('.people-listing .staff',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".news-listing-section").length){var newsSection=gsap.timeline({paused:true});if($('.news-listing-section .featured-news').length){newsSection.fromTo('.news-listing-section .featured-news',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.news-listing-wrap .news-box-wrap').length){newsSection.fromTo('.news-listing-wrap .news-box-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.news-listing-section .more-news-link').length){newsSection.fromTo('.news-listing-section .more-news-link',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".contact-section-content").length){var contactSection=gsap.timeline({paused:true,onComplete:function(){}});if($('.contact-note, .see-all-location-link').length){contactSection.fromTo('.contact-note, .see-all-location-link',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.map-svg').length){contactSection.fromTo('.map-svg',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.map-svg-mobile').length){contactSection.fromTo('.map-svg-mobile',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".news-detail-section").length){var newsDetailSection=gsap.timeline({paused:true});if($('.news-date, .news-detail-left, .news-detail-right').length){newsDetailSection.fromTo('.news-date, .news-detail-left, .news-detail-right',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".portfolio-detail-section, .people-detail-section").length){var portfolioDetailSection=gsap.timeline({paused:true});if($('.portfolio-detail-content > .row > .detail-content-left, .portfolio-detail-content > .row > .detail-content-right, .portfolio-video-wrap').length){portfolioDetailSection.fromTo('.portfolio-detail-content > .row > .detail-content-left, .portfolio-detail-content > .row > .detail-content-right, .portfolio-video-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($('.more-menu-section').length){var moremenuContent=gsap.timeline();moremenuContent.add("start-point",0).fromTo('.more-menu-section',0.05,{autoAlpha:0},{autoAlpha:1},"start-point").fromTo('.more-menu-section > .container > .row > .col-md-8 > .row > .col-sm-6:first-child > .menu-widget .widget-title',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0},"start-point").staggerFromTo('.more-menu-section .menu-widget .about-menu li',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0},0.05).staggerFromTo('.local-site-listing .local-site-menu li',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0}).staggerFromTo('.more-menu-section .menu-widget .ftr-businesses-menu li',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0},0.05).fromTo('.more-menu-section > .container > .row > .col-md-8 > .row > .col-sm-6:nth-child(2) > .menu-widget .widget-title',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0}).fromTo('.more-menu-section .more-menu-search-background',0.2,{autoAlpha:0,height:0},{autoAlpha:1,height:'100%',ease:Linear.easeIn},"start-point").fromTo('.more-menu-section .search-widget .widget-title .widget-title-txt',0.2,{autoAlpha:0,xPercent:-100},{autoAlpha:1,xPercent:0,ease:Linear.easeInOut}).fromTo('.more-menu-section #typedtext',0.0001,{autoAlpha:0},{autoAlpha:1}).staggerFromTo('.more-menu-section .typedtext-all .char, .more-menu-section .typedtext-all .whitespace',0.02,{opacity:0},{opacity:1,ease:Power1.easeIn},0.02).fromTo('.more-menu-section .search-widget .underscore',1,{autoAlpha:0},{autoAlpha:1,delay:0.3,ease:Linear.easeInOut}).add("end",1).fromTo('.more-menu-section .copyright-txt',0.1,{autoAlpha:0},{autoAlpha:1},"end").fromTo('.more-menu-section .copyright-menu',0.1,{autoAlpha:0},{autoAlpha:1},"end").fromTo('.more-menu-section .more-menu-sidebar .investor-login-widget',0.1,{autoAlpha:0},{autoAlpha:1},"end").pause();function moreMenuPopupClose(){$('.more-menu-section').modal('hide');}
$('.navbar-brand').click(function(){moreMenuPopupClose();});$('.bottom-header .navbar-nav a').click(function(){moreMenuPopupClose();});$('.btn-search').click(function(){moreMenuPopupClose();});$('.more-menu-section .about-menu a').click(function(){moreMenuPopupClose();});const tlMenuAnimation=gsap.timeline();tlMenuAnimation.fromTo('.more-menu-slants',0.5,{ease:Linear.easeOut},{ease:Linear.easeOut,delay:0.5},0).fromTo('.more-menu-slants .left-slant',0.5,{left:"-150%",ease:Linear.easeOut},{left:"-10%",ease:Linear.easeOut},0).fromTo('.more-menu-slants .right-slant',0.5,{left:"150%",ease:Linear.easeOut},{left:"-10%",ease:Linear.easeOut},0).fromTo('.more-menu-slants',0.5,{autoAlpha:0},{autoAlpha:1},0).pause();$('#more-menu-modal').on('show.bs.modal',function(){$('.more-menu-link').addClass('open');$('.more-menu-link').addClass('backLink');$('header.site-header').addClass('scrolled');$('.model_text').html('close');tlMenuAnimation.play();setTimeout(function(){$('#more-menu-modal').addClass('popup-open');moremenuContent.play();var moremenuSidebar=$(".more-menu-section .more-menu-sidebar");var moremenuSidebarBg=$(".more-menu-section .more-menu-search-background");var moremenuSidebarOffsetLeft=$(moremenuSidebar).offset().left;$(moremenuSidebarBg).css('left',moremenuSidebarOffsetLeft);},500);})
$('#more-menu-modal').on('hidden.bs.modal',function(){tlMenuAnimation.reverse();moremenuContent.reverse();$('#more-menu-modal').removeClass('popup-open');$('.more-menu-link').removeClass('open');$('.more-menu-link').removeClass('backLink');$('.model_text').html('more');if($('.banner-section').hasClass('active')&&!$('.more-menu-link').hasClass('open')){$('header.site-header').removeClass('scrolled');}})}
if($('.about-page-content-link').length){$('.about-page-content-link').on('click',function(){$.fn.fullpage.reBuild();$.fn.fullpage.moveSlideRight();return false;});}
$('.scroll-up-sec').remove();$('.scroll-down-sec').remove();$('.esg-approach-slider-buttons-wrap .nav-tabs > li > a').hover(function(){$(this).tab('show');});$('.esg-approach-slider-buttons-wrap .esg-approach-slider-buttons-title').hover(function(){$('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').tab('show');$($('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').attr('href')).removeClass('active');$('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').parent().removeClass('active');$('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').removeClass('active');$('.esg-approach-slider-buttons-wrap .nav-tabs > li:first-child > a').tab('show');});$('.banner-rf-section.esg-approach-section .row').not('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').on('mouseleave',function(){$('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').tab('show');$($('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').attr('href')).removeClass('active');$('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').parent().removeClass('active');$('.esg-approach-slider-buttons-wrap .nav-tabs > li:not(.firt-child) > a').removeClass('active');$('.esg-approach-slider-buttons-wrap .nav-tabs > li:first-child > a').tab('show');});if(document.querySelector('#fullpage')){$('#fullpage').fullpage({licenseKey:'A2B14386-2C614A99-B097591D-BAD19F4B',lockAnchors:true,anchors:['page1','page2','page3','page4'],parallaxKey:'QU5ZXzhZSWNHRnlZV3hzWVhnPWhuWQ==',parallax:true,parallaxOptions:{type:'reveal',percentage:100,property:'translate'},scrollingSpeed:1000,verticalCentered:false,fitToSectionDelay:0,controlArrows:false,scrollOverflow:true,scrollOverflowOptions:{keyBindings:{pageUp:33,pageDown:34,probeType:3}},normalScrollElements:'.dropdown-menu, .more-menu-section',onLeave:function(origin,destination,direction){onFpChange(destination);const activeSlide=origin.item.querySelector('.slide.active');var scroll=null;if(activeSlide){scroll=activeSlide.querySelector('.fp-scrollable');}else{scroll=origin.item.querySelector('.fp-scrollable');}
if(scroll){const cannotPrev=origin.index>destination.index&&scroll.fp_iscrollInstance.y<0;const cannotNext=origin.index<destination.index&&scroll.fp_iscrollInstance.y>scroll.fp_iscrollInstance.maxScrollY;if(cannotPrev||cannotNext){return false;}}
if($('.move-prev-page-sec').length){if(destination.index>1){if($(".intro-section-slants").length){introSlant.play();}
if($(".gradient-section-slants").length){gradientSlant.play();}
if($(".should-stickey").length){$('.site-header').addClass('scrolled');}}else{if($(".should-stickey").length&&!$('.more-menu-link').hasClass('open')){$('.site-header').removeClass('scrolled');}}}else{if(destination.index>0){if($(".intro-section-slants").length){introSlant.play();}
if($(".gradient-section-slants").length){gradientSlant.play();}
if($(".should-stickey").length){$('.site-header').addClass('scrolled');}}else{if($(".should-stickey").length&&!$('.more-menu-link').hasClass('open')){$('.site-header').removeClass('scrolled');}}}
if($('.move-prev-page-sec').length){if(destination.index>2){if($(".intro-section-slants").length){if(introSlant.isActive()){introSlant.progress(1);}}
if($(".gradient-section-slants").length){if(gradientSlant.isActive()){gradientSlant.progress(1);}}}}else{if(destination.index>1){if($(".intro-section-slants").length){if(introSlant.isActive()){introSlant.progress(1);}}
if($(".gradient-section-slants").length){if(gradientSlant.isActive()){gradientSlant.progress(1);}}}}
if($(destination.item).hasClass('banner-section')){if($(".video-banner-caption").length){videoCaption.play();}}else{if($(".video-banner-caption").length){}}
if($(destination.item).hasClass('home-page-second-screen')){if($(".intro-section-txt").length){setTimeout(function(){introText.play();},1000);}}
if($(destination.item).hasClass('home-page-second-screen')){if($(".sitemap-section").length){sitemapAnim.play();}}
if($(destination.item).hasClass('approach-section')){if($(".approach-section-wrap").length){strategySection.play();}
if($(".guiding-principles-block").length){strategySection.eventCallback("onComplete",function(){guidingPronciplesSection.play(0);});}}
if($(destination.item).hasClass('gradient-section-slants-content')){aboveSection=$(origin.item).attr("data-anchor");if($(".section-top-slant").length){gradientTopSlant.play();}
if($(".gradient-section-slants-content-wrap").length){gredientSection.play();}}else if($(destination.item).attr("data-anchor")==aboveSection&&!$(destination.item).hasClass('site-footer')){if($(".gradient-section-slants-content-wrap").length){gredientSection.progress(0.8);gredientSection.reverse();}
if($(".section-top-slant").length){gradientTopSlant.reverse(0.8);}}
if($(destination.item).hasClass('gradiant-counter-content-section')){aboveSection=$(origin.item).attr("data-anchor");if($(".gradiant-counter-content-section").length){countNumber();gradiantCounter.play();}}
else if($(destination.item).attr("data-anchor")==aboveSection){if($(".gradiant-counter-content-section").length){gradiantCounter.progress(1);gradiantCounter.reverse(0.1);}}
if($(destination.item).hasClass('home-page-second-screen')){aboveSection=$(origin.item).attr("data-anchor");if($(".home-page-slants").length){homeSlantHide.play();}}else if($(destination.item).hasClass("banner-section")){if($(".home-page-slants").length){homeSlantHide.reverse(0.8);}}
if($(destination.item).hasClass('move-next-page-sec')){if($(".move-next-page-sec").length){}}
if($(destination.item).hasClass('Strategy-section')){if($(".Strategy-section").length){stretagySection.play();}}
if($(destination.item).hasClass('portfolio-listing-section')){if($(".portfolio-listing-section-wrap").length){portfolioSection.play();}}
if($(destination.item).hasClass('sitemap-section')){if($(".sitemap-section").length){sitemapAnim.play();}}
if($(destination.item).hasClass('people-listing-section')){if($(".people-listing-section .portfolio-listing-section-wrap").length){peopleSection.play();}}
if($(destination.item).hasClass('news-listing-section')){if($(".news-listing-section").length){newsSection.play();}}
if($(destination.item).hasClass('contact-section')){if($(".contact-section-content").length){contactSection.play();}}
if($(destination.item).hasClass('news-detail-section')){if($(".news-detail-section").length){newsDetailSection.play();}}
if($(destination.item).hasClass('portfolio-detail-section')){if($(".portfolio-detail-section").length){portfolioDetailSection.play();}}
if($(destination.item).hasClass('people-detail-section')){if($(".people-detail-section").length){portfolioDetailSection.play();}}
if($('.move-prev-page-sec').length){if(destination.index==0&&direction=='up'){}
if(destination.index==1&&direction=='up'){if($(".intro-section-slants").length){introSlant.reverse(1);}
if($(".gradient-section-slants").length){gradientSlant.reverse(1);}}}else{if(destination.index==0&&direction=='up'){if($(".intro-section-slants").length){introSlant.reverse(1);}
if($(".gradient-section-slants").length){gradientSlant.reverse(1);}}}
if(window.matchMedia("(min-width: 768px)").matches){if(direction=='up'&&$(destination.item).hasClass('scroll-up-sec')){if($('.scroll-up-sec').length){$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').hide();$('.fp-section .fp-scroller').mousedown(function(){return false});}}
else{$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').show();}
if(direction=='down'&&$(destination.item).hasClass('scroll-down-sec')){if($('.scroll-down-sec').length){$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').hide();$('.fp-section .fp-scroller').mousedown(function(){return false});}}
else{$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').show();}}
if(window.matchMedia("(min-width: 992px)").matches){if($('.Strategy-section').length||$('.gradient-section-slants-content').length){if(direction=='up'&&$(destination.item).hasClass('Strategy-section')){$('.Strategy-intro .sideStick').insertAfter(".site-header .bottom-header");$('.sideStick .navbar-collapse').addClass("container");$.fn.fullpage.reBuild();}
else if(direction=='down'&&$(destination.item).hasClass('gradient-section-slants-content')){$('.site-header .sideStick').insertBefore(".Strategy-intro.sub-menu .container .dropdown");$('.sideStick .navbar-collapse').removeClass("container");$.fn.fullpage.reBuild();}
if(direction=='up'&&$(destination.item).hasClass('move-prev-page-sec')){$('.site-header .sideStick').insertBefore(".Strategy-intro.sub-menu .container .dropdown");$('.sideStick .navbar-collapse').removeClass("container");$.fn.fullpage.reBuild();}}}},afterLoad:function(origin,destination,direction){if(!$('html').hasClass('fullpage-ready')){$('html').addClass('fullpage-ready');}
if($(destination.item).hasClass('home-page-second-screen')){if($(".intro-section-txt").length){introText.play();}}
if($(destination.item).hasClass('about-section')){if($(".about-section").length){aboutSection.play();}}
if($('.move-prev-page-sec').length){if(destination.index==0){$.fn.fullpage.silentMoveTo('page2',0);}}
if($(destination.item).hasClass('Strategy-section')){if($(".Strategy-section").length){stretagySection.play();}}
if($(destination.item).hasClass('approach-section')){if($(".approach-section-wrap").length){strategySection.play();}
if($(".guiding-principles-block").length){strategySection.eventCallback("onComplete",function(){guidingPronciplesSection.play(0);});}}
if($(destination.item).hasClass('portfolio-listing-section')){if($(".portfolio-listing-section-wrap").length){portfolioSection.play();}}
if($(destination.item).hasClass('people-listing-section')){if($(".people-listing-section .portfolio-listing-section-wrap").length){peopleSection.play();}}
if($(destination.item).hasClass('news-listing-section')){if($(".news-listing-section").length){newsSection.play();}}
if($(destination.item).hasClass('contact-section')){if($(".contact-section-content").length){contactSection.play();}}
if($(destination.item).hasClass('news-detail-section')){if($(".news-detail-section").length){newsDetailSection.play();}}
if($(destination.item).hasClass('portfolio-detail-section')){if($(".portfolio-detail-section").length){setTimeout(function(){$.fn.fullpage.reBuild();},300);}
portfolioDetailSection.play();}
if($(destination.item).hasClass('portfolio-detail-banner')){if($(".portfolio-detail-section").length){setTimeout(function(){$.fn.fullpage.reBuild();},100);}}
if($(destination.item).hasClass('people-detail-section')){if($(".people-detail-section").length){portfolioDetailSection.play();}}
if(window.matchMedia("(min-width: 768px)").matches){if(direction=='up'&&$(destination.item).hasClass('scroll-up-sec')){if($('.scroll-up-sec').length){$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').hide();}}
else if(direction=='down'&&$(destination.item).hasClass('scroll-down-sec')){if($('.scroll-down-sec').length){$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').hide();$('.fp-section .fp-scroller').mousedown(function(){return false});}}
else{$('.iScrollVerticalScrollbar.iScrollLoneScrollbar').show();$('.fp-section .fp-scroller').mousedown(function(){return false});}}
if(window.matchMedia("(min-width: 992px)").matches&&$(destination.item).hasClass('Strategy-section')){const scrollable=$('.fp-section.active').find('.fp-scrollable')[0];if($('.sideStick').length&&scrollable&&typeof scrollable!==undefined){const scrollInstance=scrollable.fp_iscrollInstance;scrollInstance.on('scrollStart',function(){if(scrollInstance.y<=0){$('.Strategy-intro .sideStick').insertAfter(".site-header .bottom-header");$('.sideStick .navbar-collapse').addClass("container");$.fn.fullpage.reBuild();}});scrollInstance.on('scrollEnd',function(){});}}},onSlideLeave:function(section,origin,destination,direction){if($(destination.item).hasClass('about-section')){if($(".about-section").length){aboutSection.play();}}},afterRender:function(){}});}
setTimeout(function(){},1000);if($('.people-listing-section').length){$('.people-listing').isotope({});}
if($('.switch-view').length){$('.switch-view a').click(function(e){e.preventDefault();$switch=$(this);var selectedView=$switch.attr('data-view');if(selectedView=='grid'){$('.people-listing').removeClass('list-view');$('.people-listing').isotope({});}else if(selectedView=='list'){$('.people-listing').addClass('list-view');$('.people-listing').isotope({});}
$('.people-listing').isotope({});$('.switch-view a').removeClass('active');$switch.addClass('active');setTimeout(function(){$.fn.fullpage.reBuild();},600);});}
if($('.portfolio-grid').length){var buttonFilters={};var buttonFilter;var qsRegex;var $portfolioGrid=$('.portfolio-grid').isotope({itemSelector:'.grid-item',masonry:{columnWidth:0,},getSortData:{alphabetical:'[data-name]',year:'[data-year] parseInt',},filter:function(){var $this=$(this);var searchResult=qsRegex?$this.attr('data-name').match(qsRegex):true;var buttonResult=buttonFilter?$this.is(buttonFilter):true;return searchResult&&buttonResult;},});$portfolioGrid.on('arrangeComplete',function(event,filteredItems){if(filteredItems.length==0){$('.no-data-div').show();}else{$('.no-data-div').hide();}
setTimeout(function(){$.fn.fullpage.reBuild();},600);});$('.filter-group').on('click','.dropdown-menu a',function(){var $this=$(this);var $buttonGroup=$this.parents('.dropdown-menu');var filterGroup=$buttonGroup.attr('data-filter-group');buttonFilters[filterGroup]=$this.attr('data-filter');buttonFilter=concatValues(buttonFilters);$portfolioGrid.isotope();setTimeout(function(){$.fn.fullpage.reBuild();},600);});var $quicksearch=$('#investmentsSearch').keyup(debounce(function(){qsRegex=new RegExp($quicksearch.val(),'gi');$portfolioGrid.isotope();}));$('#sorts').on('click','.dropdown-menu a',function(){var sortByValue=$(this).attr('data-sort-by');$('.portfolio-grid').isotope({sortBy:sortByValue});setTimeout(function(){$.fn.fullpage.reBuild();},600);});$('.dropdown-menu').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','.portfolio-sorting-wrap .dropdown-menu a, .people-filter .dropdown-menu a',function(event){$buttonGroup.find('.selected').removeClass('selected');var $button=$(event.currentTarget);$button.addClass('selected');});setTimeout(function(){$.fn.fullpage.reBuild();},600);});function concatValues(obj){var value='';for(var prop in obj){value+=obj[prop];}
return value;}
function debounce(fn,threshold){var timeout;threshold=threshold||100;return function debounced(){clearTimeout(timeout);var args=arguments;var _this=this;function delayed(){fn.apply(_this,args);}
timeout=setTimeout(delayed,threshold);};}}
if($('.people-listing').length){var buttonFilters={};var buttonFilter;var qsRegex;var $peopleGrid=$('.people-listing').isotope({itemSelector:'.people-grid',filter:function(){var $this=$(this);var $name=$(this).find('.team-desc h4 > span');var searchResult=qsRegex?$name.text().match(qsRegex):true;var buttonResult=buttonFilter?$this.is(buttonFilter):true;return searchResult&&buttonResult;},});$peopleGrid.on('arrangeComplete',function(event,filteredItems){if(filteredItems.length==0){$('.no-data-div').show();}else{$('.no-data-div').hide();}
setTimeout(function(){$.fn.fullpage.reBuild();},600);});$peopleGrid.isotope();$('.people-filter').on('click','.dropdown-menu a',function(){var $this=$(this);var $buttonGroup=$this.parents('.dropdown-menu');var filterGroup=$buttonGroup.attr('data-filter-group');buttonFilters[filterGroup]=$this.attr('data-filter');buttonFilter=concatValues(buttonFilters);$peopleGrid.isotope();setTimeout(function(){$.fn.fullpage.reBuild();},600);});var $quicksearch=$('#investmentsSearch').keyup(debounce(function(){qsRegex=new RegExp($quicksearch.val(),'gi');$peopleGrid.isotope();}));$('.dropdown-menu').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','.portfolio-sorting-wrap .dropdown-menu a, .people-filter .dropdown-menu a',function(event){$buttonGroup.find('.selected').removeClass('selected');var $button=$(event.currentTarget);$button.addClass('selected');});setTimeout(function(){$.fn.fullpage.reBuild();},600);});function concatValues(obj){var value='';for(var prop in obj){value+=obj[prop];}
return value;}
function debounce(fn,threshold){var timeout;threshold=threshold||100;return function debounced(){clearTimeout(timeout);var args=arguments;var _this=this;function delayed(){fn.apply(_this,args);}
timeout=setTimeout(delayed,threshold);};}
$('.dropdown-menu').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','.portfolio-sorting-wrap .dropdown-menu a, .people-filter .dropdown-menu a',function(event){$buttonGroup.find('.selected').removeClass('selected');var $button=$(event.currentTarget);$button.addClass('selected');});setTimeout(function(){$.fn.fullpage.reBuild();},600);});function concatValues(obj){var value='';for(var prop in obj){value+=obj[prop];}
return value;}}
$('.case-studies-slider').slick({nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',dots:false,infinite:true,speed:300,slidesToShow:1,centerPadding:'0px',});$('.partner-quotes-slider').slick({nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',dots:false,arrows:true,infinite:true,autoplay:true,autoplaySpeed:2000,slidesToShow:1,centerPadding:'0px',});$('.case-study-grid').slick({nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',dots:false,arrows:true,infinite:false,autoPlay:true,speed:300,slidesToShow:2,centerPadding:'0px',responsive:[{breakpoint:575,settings:{slidesToShow:1,centerMode:true,}},]});dropDownOnHover();function dropDownOnHover(){const showClass="show";$('.bottom-header .navbar ul.navbar-nav li.dropdown').hover(function(){$(this).find('.dropdown-menu').stop(true,true).delay(100).fadeIn(300);$(this).addClass(showClass);$(this).find('.dropdown-menu').addClass(showClass);},function(){$(this).find('.dropdown-menu').stop(true,true).delay(100).fadeOut(300);$(this).removeClass(showClass);$(this).find('.dropdown-menu').removeClass(showClass);});}
$('.spotlight-slider').slick({nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',dots:false,infinite:false,speed:300,slidesToShow:2,centerPadding:'0px',responsive:[{breakpoint:991,settings:{slidesToShow:1,centerMode:true,}},]});if(!$('.sitemap-bottom-section').length){$('.sitemap-top-section').removeClass('col-md-8');$('.sitemap-top-section').addClass('col-md-12');$('.sitemap-section').css('background-color','#E6E6E3');$('.home-page-scroll-section').css('background-color','#E6E6E3');$('.home-page-scroll-sec-left').addClass('d-none');$('.home-page-scroll-sec-right').removeClass('col-md-8');$('.home-page-scroll-sec-right').addClass('col-md-12');}
if($(".sitemap-top-wrap .row .sitemap-single-page").length==3){$(".sitemap-top-wrap .row .sitemap-single-page").removeClass('col-xl-3');$(".sitemap-top-wrap .row .sitemap-single-page").addClass('col-xl-4');}
if($(".sitemap-top-wrap .row .sitemap-single-page").length==2){$(".sitemap-top-wrap .row .sitemap-single-page").removeClass('col-xl-3');$(".sitemap-top-wrap .row .sitemap-single-page").addClass('col-xl-6');}
if($(".sitemap-top-wrap .row .sitemap-single-page").length==1){$(".sitemap-top-wrap .row .sitemap-single-page").removeClass('col-xl-3 col-sm-6');$(".sitemap-top-wrap .row .sitemap-single-page").addClass('col-xl-12 col-sm-12');}
if(window.matchMedia("(min-width: 1200px)").matches){if($(".sitemap-top-wrap .row .sitemap-single-page").length>4){sitemapSlider();}}
if(window.matchMedia("(max-width: 1199px)").matches){if($(".sitemap-top-wrap .row .sitemap-single-page").length>1){sitemapSlider();}}
if(window.matchMedia("(min-width: 768px)").matches){explandContent();}
if(window.matchMedia("(max-width: 767px)").matches){explandContentMobile();}
if(window.matchMedia("(min-width: 992px)").matches){tabExpandContent();}
if(window.matchMedia("(max-width: 991px)").matches){tabExpandContentMobile();}
if($('.news-detail-content').length){SocialURL();}
function explandContent(){$('.impact-block-wrapper .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').slideUp(300);$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').slideDown(400);$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
$this.addClass("active");setTimeout(function(){$.fn.fullpage.reBuild();},600);});}
function explandContentMobile(){$('.impact-block-wrapper .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').slideUp(300);$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').slideDown(300);$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
setTimeout(function(){$.fn.fullpage.reBuild();},600);$this.addClass("active");});}
function tabExpandContent(){$('.management-boxes-wrap .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideUp(300);$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideDown(300);$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
setTimeout(function(){$.fn.fullpage.reBuild();},600);$this.addClass("active");});}
function tabExpandContentMobile(){$('.management-boxes-wrap .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideUp(300);$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideDown(300);$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
setTimeout(function(){$.fn.fullpage.reBuild();},600);$this.addClass("active");});}
function countNumber(){setTimeout(function(){$('.count-no .anim').each(function(){var $this=$(this);var $AnimFixValue=$(this).find('.fix-value');var $AnimStartValue=$(this).find('.start-value');var AnimText=$(this).text();jQuery({Counter:0}).animate({Counter:$AnimFixValue.text()},{duration:1000,delay:4000,easing:'swing',step:function(){if(AnimText.toString().indexOf('.')!=-1)
{$AnimStartValue.text((this.Counter).toFixed(1));}else{$AnimStartValue.text(Math.ceil(this.Counter));}}});});},300);};function fpGenerate(){if($(".fp-fixed").length){$fpFixed=$(".fp-fixed");fpCount=$("#fullpage .section").length;$fpFixed.html("");$("#fullpage .section").each(function(i,e){var fpGroup=$(e).attr("data-fp-group");if(typeof fpGroup==="undefined"){fpGroup="";}else{fpGroup="group-"+$(e).attr("data-fp-group");}
if($("."+fpGroup).length==0){$fpFixed.append('<div class="fp-group-section '+fpGroup+'"></div>');}
var fpStyles=$(e).attr("data-fp-style");if(typeof fpStyles==="undefined"){fpStyles="";}
$("."+fpGroup).append("<div class='fp-synced-section' style='"+fpStyles+"'></div>");var fpInr="";if(typeof $(e).find(".fp-fixed-inr")[0]!=="undefined"){fpInr=$(e).find(".fp-fixed-inr")[0].innerHTML;}
$("."+fpGroup).append(fpInr);});$fpFixed.find(".fp-group-section:first-of-type").addClass("active").find(".fp-synced-section:first-of-type").addClass("active");}}
function onFpChange(destination){var fpGroup=$(destination.item).attr("data-fp-group");var $fpGroupAll=$(".fp-fixed .fp-group-section");$fpGroupAll.removeClass("active");$thisGroup=$(".fp-fixed .group-"+fpGroup);$thisGroup.addClass("active");var $fpBgAll=$(".fp-fixed .fp-synced-section");$fpBgAll.removeClass("active");$($fpBgAll[destination.index]).addClass("active");var activeIndex=$thisGroup.find(".fp-synced-section").index($(".fp-synced-section.active"));if(activeIndex>0){$thisGroup.find(".fp-fixed-content").addClass("non-first");}else{$thisGroup.find(".fp-fixed-content").removeClass("non-first");}}
if($('.strategies-tab-section').length){accordionRebuilt();accordionScrolling();}
function accordionRebuilt(){$('#stratagyAccrodion').on('shown.bs.collapse',function(){$.fn.fullpage.reBuild();});$('#stratagyAccrodion').on('hidden.bs.collapse',function(){$.fn.fullpage.reBuild();});}
function accordionScrolling(){$(".strategies-tabs-content .card-header button").click(function(){const scrollable=$('.fp-section.active').find('.fp-scrollable')[0];if(scrollable&&typeof scrollable!==undefined){const scrollInstance=scrollable.fp_iscrollInstance;const scrollSection=$('.Strategy-intro').height();console.log(scrollSection);scrollInstance.scrollTo(0,-scrollSection,1000);setTimeout(function(){scrollInstance.refresh();},1000+150);}})}
function SocialURL(){$(".sharePage ul li a").click(function(){var urlPath=window.location.href;if($(this).hasClass('addthis_button_email')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/email/offer?url="+urlPath);}else if($(this).hasClass('addthis_button_linkedin')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/linkedin/offer?url="+urlPath);}else if($(this).hasClass('addthis_button_twitter')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url="+urlPath);}else if($(this).hasClass('addthis_button_facebook')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url="+urlPath);}});}
$('.strategies-tabs .nav-link').click(function(){setTimeout(function(){$.fn.fullpage.reBuild();},600);});$('.portfolio-sorting-wrap .dropdown-menu a, .people-listing-section .dropdown-menu a').click(function(){console.log('click');$('.portfolio-sorting-wrap .dropdown-menu a, .people-listing-section .dropdown-menu a').removeClass('selected');$(this).addClass('selected');$(this).closest('.dropdown-menu').closest('.dropdown').find(".psorting").find('.selected-value').text($(this).text());});esgApproachSliderButtonHeight();setTimeout(function(){$('.more-menu-link.backLink').addClass('open');},10);$('.more-menu-link.backLink').on('click',function(){window.history.go(-1);changePageSlantColor();$(this).removeClass('open');return false;});$('.more-menu-section ul li a').on('click',function(){$('.more-menu-link').removeClass('open');});$('.navbar-brand').on('click',function(){console.log("Clicked");$('.more-menu-link').removeClass('open');});$('.scroll-down-link').on('click',function(e){e.preventDefault();fullpage_api.moveSectionDown();});$('.dropdown').on('shown.bs.dropdown',function(e){setTimeout(function(){$(e.target).addClass('shown');},350);});$('.dropdown').on('hide.bs.dropdown',function(e){$(e.target).removeClass('shown');});}
function unload(){if(document.querySelector('#fullpage')){$.fn.fullpage.destroy('all');}}
function moremenuSidebarBgPlacement(){if($('.more-menu-sidebar').length){var moremenuSidebar=$(".more-menu-section .more-menu-sidebar");var moremenuSidebarBg=$(".more-menu-section .more-menu-search-background");var moremenuSidebarOffsetLeft=$(moremenuSidebar).offset().left;$(moremenuSidebarBg).css('left',moremenuSidebarOffsetLeft);}}
function stickySidebar(){if($(".sideStick").length&&window.matchMedia("(min-width: 768px)").matches){if($('body').find('.matchWrap').length){$(".sideStick").stick_in_parent({parent:'.matchWrap',offset_top:100});var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});var windowWidth=$(window).width();$(window).resize(function(){var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();if($(window).width()!=windowWidth){$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});}});}else{$(".sideStick").stick_in_parent({parent:'.news-detail-content',offset_top:100,spacer:false,});var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});var windowWidth=$(window).width();$(window).resize(function(){var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();if($(window).width()!=windowWidth){$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});}});}}}
function moveToNextPageOnSroll(){changePageSlantColor();var currentPage;if(document.location.pathname=="/esgandimpact/"){currentPage='/esgandimpact/';}else{currentPage=document.location.pathname.match(/[^\/]+$/);}
if(currentPage=='/esgandimpact/'){swup.loadPage({url:'/esgandimpact/active-governance-and-stewardship.html',});}else{if($(".submenu-header .navbar-nav > li.active").length){if(!$(".submenu-header .navbar-nav > li.active").is(':last-child')){navNextLink=$(".submenu-header .navbar-nav > li.active a").parent().next().children("a").attr("href");swup.loadPage({url:navNextLink,});}}}}
function moveToPrevPageOnSroll(){changePageSlantColor();var currentPage=document.location.pathname.match(/[^\/]+$/);if(currentPage=='active-governance-and-stewardship.html'){swup.loadPage({url:'/esgandimpact/',});}else{if($(".submenu-header .navbar-nav > li.active").length){navNextLink=$(".submenu-header .navbar-nav > li.active a").parent().prev().children("a").attr("href");swup.loadPage({url:navNextLink,});}}}
function setVideoHeight(){setTimeout(function(){var windowHgt=$('html').height();$('.video-banner .embed-responsive').css('max-height',windowHgt);},1000);}
function splitLinesAnimation(className,isChange=false){if(sessionStorage.getItem('thisPage')=='index'){if(isChange){$(className).html(sessionStorage.getItem("aboutHtml"));}
if($(className).length){$(className).splitLines({tag:'<div>',keepHtml:true});}
if($("[data-splitting]").length){Splitting();}
$(".intro-section-txt.animation-complete .highlighted-txt .char").css("color",aboutHighlightTextColor);}}
function updateHeight(){if(window.matchMedia("(min-width: 768px)").matches&&window.matchMedia("(min-height: 750px)").matches){if($('.home-page-second-screen').length){setTimeout(function(){var h1=$('.home-page-second-screen-wrap').outerHeight();var h2=$('.sitemap-section').outerHeight();var h3=$('.home-page-second-screen-wrap .home-page-scroll-sec').outerHeight(true);var h4=h1-h2-h3;$('.intro-section').css("height",h4);},500);}}}
function sitemapSlider(){$('.sitemap-top-wrap .row').slick({nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',dots:false,infinite:false,speed:300,slidesToShow:4,responsive:[{breakpoint:1200,settings:{slidesToShow:3,}},{breakpoint:577,settings:{slidesToShow:2,}},]});}
function caseStudyGrid(){if($(".case-study-grid .case-study-item").length==2){$(".case-study-grid .case-study-item").removeClass('col-md-4');$(".case-study-grid .case-study-item").addClass('col-md-6');}
if($(".case-study-grid .case-study-item").length==1){$(".case-study-grid .case-study-item").removeClass('col-md-4 col-6');$(".case-study-grid .case-study-item").addClass('col-lg-7 col-md-8');$(".case-study-grid").addClass('justify-content-center');}}
function esgApproachSliderButtonHeight(){setTimeout(function(){if(window.matchMedia("(min-width: 768px)").matches){var n=$('.esg-approach-slider-button').length-1;var totalHeight=$('.banner-section-wrapper .esg-approach-slider-buttons-wrap').outerHeight()-$('.esg-approach-slider-buttons-title').outerHeight();$('.esg-approach-slider-buttons').css('height',totalHeight);var height=totalHeight/n;$('.esg-approach-slider-button').css('height',height);}},500);if(window.matchMedia("(max-width: 767px)").matches){if($(".esg-approach-section").length){var tab_selector,tablist,current_active,list_lenth;tab_selector=".esg-approach-section";tablist=$('.esg-approach-section .nav-tabs > li > a[data-toggle="tab"]');list_lenth=tablist.length;$(tablist).click(function(e){$.fn.fullpage.reBuild();});const $tabsToDropdown=$(".tabs-to-dropdown");function generateDropdownMarkup(container){const $navWrapper=container.find(".esg-approach-slider-buttons-wrap");const $navPills=container.find(".nav-tabs");const firstTextLink=$navPills.find("li:first-child a").text();const $items=$navPills.find("li");const markup=`
            <div class="dropdown d-md-none">
              <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ${firstTextLink}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"> 
                ${generateDropdownLinksMarkup($items)}
              </div>
            </div>
          `;$navWrapper.prepend(markup);}
function generateDropdownLinksMarkup(items){let markup="";items.each(function(){const textLink=$(this).find("a").text();markup+=`<a class="dropdown-item" href="#">${textLink}</a>`;});return markup;}
function showDropdownHandler(e){const $this=$(e.target);const $dropdownToggle=$this.find(".dropdown-toggle");const dropdownToggleText=$dropdownToggle.text().trim();const $dropdownMenuLinks=$this.find(".dropdown-menu a");const dNoneClass="d-none";$dropdownMenuLinks.each(function(){const $this=$(this);if($this.text()==dropdownToggleText){$this.addClass(dNoneClass);}else{$this.removeClass(dNoneClass);}});}
function clickHandler(e){e.preventDefault();const $this=$(this);const index=$this.index();const text=$this.text();$this.closest(".dropdown").find(".dropdown-toggle").text(`${text}`);$this.closest($tabsToDropdown).find(`.nav-tabs li:eq(${index}) a`).tab("show");setTimeout(function(){$.fn.fullpage.reBuild();},500);}
function shownTabsHandler(e){const $this=$(e.target);const index=$this.parent().index();const $parent=$this.closest($tabsToDropdown);const $targetDropdownLink=$parent.find(".dropdown-menu a").eq(index);const targetDropdownLinkText=$targetDropdownLink.text();$parent.find(".dropdown-toggle").text(targetDropdownLinkText);}
$tabsToDropdown.each(function(){const $this=$(this);const $pills=$this.find('a[data-toggle="pill"]');generateDropdownMarkup($this);const $dropdown=$this.find(".dropdown");const $dropdownLinks=$this.find(".dropdown-menu a");$dropdown.on("show.bs.dropdown",showDropdownHandler);$dropdownLinks.on("click",clickHandler);$pills.on("shown.bs.tab",shownTabsHandler);});}}}
function esgTab(){if(window.matchMedia("(min-width: 992px)").matches){$(window).bind('scroll',function(){if($(window).scrollTop()>0){$('.Strategy-intro .sideStick').insertAfter(".site-header .bottom-header");$('.sideStick .navbar-collapse').addClass("container");}
else{$('.site-header .sideStick').insertBefore(".Strategy-intro.sub-menu .container .dropdown");$('.sideStick .navbar-collapse').removeClass("container");}});}
if(window.matchMedia("(max-width: 991px)").matches&&$(".our-strategies-tabs-content").length){var tab_selector,tablist,current_active,list_lenth;tab_selector=".our-strategies-section";tablist=$('.our-strategies-section .nav-tabs > li > a[data-toggle="tab"]');list_lenth=tablist.length;$(".our-strategies-section .tab_nav").click(function(e){e.preventDefault();$(tablist).each(function(index){if($(this).hasClass("active")){current_active=index;}});if($(this).hasClass("prev")){if(current_active!==0){$(tablist[current_active-1]).tab("show");}else{$(tablist[list_lenth-1]).tab("show");}}else if($(this).hasClass("next")){if(current_active!=list_lenth-1){$(tablist[current_active+1]).tab("show");}else{$(tablist[0]).tab("show");}}});}}