var scrollTopFlag=false;var scrollBottomFlag=false;var scrollBottomCounter=0;var lastScrollTop=0;var isEdge=!isIE&&!!window.StyleMedia;var isIE=false||!!document.documentMode;var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==="[object SafariRemoteNotification]";})(!window['safari']||(typeof safari!=='undefined'&&safari.pushNotification));var iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;var isAnimationBackward=false,isAnimationForward=false;var aboveSection=null;var aboutHighlightTextColor="#1CA6DF";var isMobile=false,isDesktop=false;if(isIE||isEdge){$('body').addClass('edge-browser');}
if(iOS){$('body').addClass('ios-browser');}
$(document).ready(function(){if($(".should-stickey").length){if($(window).scrollTop()>0){$('.site-header').addClass('scrolled');}else{$('.site-header').removeClass('scrolled');}}
setTimeout(function(){if($(".no-fullpage").length){$(".no-fullpage").animate({opacity:1},20);}},1000);});$(window).scroll(function(e){if($(".should-stickey").length){if($(window).scrollTop()>0){$('.site-header').addClass('scrolled');}else{$('.site-header').removeClass('scrolled');}}});$(window).resize(function(){if(window.matchMedia("(min-width: 992px)").matches){moremenuSidebarBgPlacement();}
stickySidebar();setVideoHeight();splitLinesAnimation(".intro-section-txt",true);});const options=[{from:'(.*)',to:'(.*)',in:function(next){animateSlantIn(next);},out:function(next){if(isAnimationBackward||isAnimationForward){animateFadeOutLeft(next);isAnimationBackward=isAnimationForward=false;}else{animateSlantOut(next);}}},{from:'(.*)',to:'/more-menu',in:function(next){animateMenuIn(next);},out:function(next){animateMenuOut(next);}},{from:'(.*)',to:'detail-page-transition',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/news/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/portfolio/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},{from:'(.*)/people/(.*)',to:'(.*)/',in:function(next){animateFadeIn(next);},out:function(next){animateFadeOutLeft(next);}},];const swup=new Swup({animateHistoryBrowsing:true,plugins:[new SwupScrollPlugin(),new SwupJsPlugin(options),new SwupScriptsPlugin(),new SwupBodyClassPlugin(),new SwupPreloadPlugin()]});init();swup.on('contentReplaced',init);swup.on('willReplaceContent',unload);swup.on('clickLink',changePageSlantColor);swup.on('popState',changePageSlantColor);if($('.scroll-up-sec').length){var scrollUpSecOffsetTop=$('.scroll-up-sec').offset().top;var scrollUpSecHeight=$('.scroll-up-sec').outerHeight();var scrollUpSecOffsetBottom=scrollUpSecOffsetTop+scrollUpSecHeight;}
swup.on('contentReplaced',function(){if($(".no-fullpage").length){swup.scrollTo(scrollUpSecOffsetBottom);}});if($(".no-fullpage").length){swup.scrollTo(scrollUpSecOffsetBottom);}
swup.on('transitionEnd',function(){scrollTopFlag=false;setTimeout(function(){if($(".no-fullpage").length){$(".no-fullpage").animate({opacity:1},20);}},1000);});swup.on('scrollDone',function(){setTimeout(function(){if($(".no-fullpage").length){$(".no-fullpage").animate({opacity:1},20);}},1000);});swup.on('popState',function(event){var fromPage=sessionStorage.getItem('thisPage');var toPage=getPageNameFromPath(event.target.location.pathname);isAnimationBackward=(fromPage.startsWith("/news/*")&&toPage.startsWith("/news"))||(fromPage.startsWith("/portfolio/*")&&toPage.startsWith("/portfolio"))||(fromPage.startsWith("/people/*")&&toPage.startsWith("/people"));isAnimationForward=(fromPage.startsWith("/news")&&toPage.startsWith("/news/*"))||(fromPage.startsWith("/portfolio")&&toPage.startsWith("/portfolio/*"))||(fromPage.startsWith("/people")&&toPage.startsWith("/people/*"));});swup.on('pageView',function(){setLocation();setMenuActive();setVideoHeight();});document.addEventListener("DOMContentLoaded",function(event){setLocation();setMenuActive();setVideoHeight();});function setLocation(){var urlPath=window.location.pathname;var thisPage=getPageNameFromPath(urlPath);var lastPage=sessionStorage.getItem('thisPage');sessionStorage.setItem('thisPage',thisPage);sessionStorage.setItem('lastPage',lastPage);}
function getPageNameFromPath(url){var urlArr=url.split('/');var pageName="index";if(urlArr[urlArr.length-1].length){pageName=urlArr[urlArr.length-1];}
return pageName;}
function setMenuActive(){if(sessionStorage.getItem('thisPage')=="more-menu"){$('.about-menu li a').removeClass('active')
$('.about-menu li').each(function(){var $anc=$(this).find('a');var href=$anc.attr('href');var pageName=getPageNameFromPath(href);var lastPage=sessionStorage.getItem('lastPage');if(pageName==lastPage){$anc.addClass('active');}});}}
function animateFadeIn(next){const tlFadeIn=gsap.timeline({paused:true});tlFadeIn.fromTo('.site-content-cover',0.6,{autoAlpha:0},{autoAlpha:1,ease:Linear.easeOut,onComplete:next},0).play();}
function animateFadeOutLeft(next){const tlFadeOutLeft=gsap.timeline({paused:true});tlFadeOutLeft.to('.site-content-cover',0.6,{xPercent:-100,autoAlpha:0,ease:Linear.easeOut,onComplete:next},0).play();}
function animateSlantIn(next){const tlSlantIn=gsap.timeline({paused:true});tlSlantIn.to('.page-slants',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants .left-slant',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.page-slants .right-slant',0.4,{autoAlpha:0,ease:Linear.easeOut,},0).to('.page-slants .left-slant',0,{yPercent:0,ease:Linear.easeIn},1).to('.page-slants .right-slant',0,{yPercent:0,ease:Linear.easeIn,onComplete:next},1).play();}
function animateSlantOut(next){const tlSlantOut=gsap.timeline({paused:true});tlSlantOut.to('.page-slants',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.page-slants .left-slant',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.page-slants .right-slant',0,{autoAlpha:1,ease:Linear.easeOut,},0).to('.page-slants .left-slant',1,{yPercent:-80,ease:Linear.easeIn},0).to('.page-slants .right-slant',1,{yPercent:-80,ease:Linear.easeIn,onComplete:next},0).play();}
function animateMenuIn(next){const tlMenuIn=gsap.timeline({paused:true});tlMenuIn.to('.more-menu-slants',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.more-menu-slants .left-slant',0.4,{autoAlpha:0,ease:Linear.easeOut},0).to('.more-menu-slants .right-slant',0.4,{autoAlpha:0,ease:Linear.easeOut,},0).to('.more-menu-slants .left-slant',0,{left:'-100%',ease:Linear.easeIn},0.4).to('.more-menu-slants .right-slant',0,{left:'100%',ease:Linear.easeIn,onComplete:next},0.4).play();}
function animateMenuOut(next){const tlMenuOut=gsap.timeline({paused:true});tlMenuOut.to('.more-menu-slants',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.more-menu-slants .left-slant',0,{autoAlpha:1,ease:Linear.easeOut},0).to('.more-menu-slants .right-slant',0,{autoAlpha:1,ease:Linear.easeOut,},0).to('.more-menu-slants .left-slant',0.4,{left:'-10%',ease:Linear.easeIn},0).to('.more-menu-slants .right-slant',0.4,{left:'-10%',ease:Linear.easeIn,onComplete:next},0).play();}
function changePageSlantColor(){if($('.page-slants').length){var leftPageSlant,rightPageSlant;if($('.page-slants > .left-slant').length){leftPageSlant=$('.page-slants > .left-slant');}
if($('.page-slants > .right-slant').length){rightPageSlant=$('.page-slants > .right-slant');}
setTimeout(function(){var targetLinkHrefLocation=document.location.pathname.match(/[^\/]+$/);if(targetLinkHrefLocation&&targetLinkHrefLocation.length){var targetLinkHref=(targetLinkHrefLocation[0]);if(targetLinkHref=="about-us"){$(leftPageSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#1c2156');$('body').css('background-color','#0047bb');}else if(targetLinkHref=="strategy-impact"){$(leftPageSlant).css('background-color','#1c2156');$(rightPageSlant).css('background-color','#abcae9');$('body').css('background-color','#cfcdc8');}else if(targetLinkHref=="people"){$(leftPageSlant).css('background-color','#1c2156');$(rightPageSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="portfolio"){$(leftPageSlant).css('background-color','#1c2156');$(rightPageSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="portfolio-detail"){$(leftPageSlant).css('background-color','#1e3278');$(rightPageSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="people-detail"){$(leftPageSlant).css('background-color','#1e3278');$(rightPageSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="news"){$(leftPageSlant).css('background-color','#1e3278');$(rightPageSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="news-detail"){$(leftPageSlant).css('background-color','#1e3278');$(rightPageSlant).css('background-color','#e6e6e3');$('body').css('background-color','#e6e6e3');}else if(targetLinkHref=="contact"){$(leftPageSlant).css('background-color','#0047bb');$(rightPageSlant).css('background-color','#1e3278');$('body').css('background-color','#1e3278');}else{$(leftPageSlant).css('background-color','#1e3278');$(rightPageSlant).css('background-color','#1C2156');$('body').css('background-color','#1C2156');}}},10);}}
function init(){fpGenerate();var $mapSvgWrap=$('.map-svg-wrap');var $mapSvgMobileWrap=$('.map-svg-mobile-wrap');if($mapSvgWrap.length){if(localStorage.getItem('map-svg')==="undefined"||localStorage.getItem('map-svg')==null){localStorage.setItem("map-svg",$mapSvgWrap.html());localStorage.setItem("map-svg-mobile",$mapSvgMobileWrap.html());}
isDesktop=isMobile=false;var mq=window.matchMedia('(min-width: 576px)');if(mq.matches){isDesktop=true;$mapSvgMobileWrap.empty();}else{isMobile=true
$mapSvgWrap.empty();}
var visibilityStyle={opacity:"1",visibility:"visible"}
$(window).resize(function(){isDesktop=isMobile=false;if(mq.matches){isDesktop=true;$mapSvgMobileWrap.empty();$mapSvgWrap.html(localStorage.getItem("map-svg"));$mapSvgWrap.find('svg').css(visibilityStyle);}else{isMobile=true
$mapSvgWrap.empty();$mapSvgMobileWrap.html(localStorage.getItem("map-svg-mobile"));$mapSvgMobileWrap.find('svg').css(visibilityStyle);}});}
if($('.video-wrap').length){$('.video-wrap').each(function(){const player=new Plyr($(this).find('.video-frame'));$(this).find('.videoPlayLink').on('click',function(){$(this).parent().find('.img-fluid').hide();$(this).parent().find('.video-caption').hide();$(this).hide();player.play();});});}
var isIE=false||!!document.documentMode;var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==="[object SafariRemoteNotification]";})(!window['safari']||(typeof safari!=='undefined'&&safari.pushNotification));var iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;if(isIE||isEdge){$('body').addClass('edge-browser');}
if(iOS){$('body').addClass('ios-browser');}
changePageSlantColor();if(window.matchMedia("(min-width: 992px)").matches){moremenuSidebarBgPlacement();}
$(".more-menu-sidebar .search-widget #keys").focus(function(){$('.more-menu-sidebar .typedtext').hide();$('.more-menu-sidebar .underscore').hide();});$('.more-menu-sidebar .search-widget #keys').blur(function(){if(!$(this).val()){$('.more-menu-sidebar .typedtext').show();$('.more-menu-sidebar .underscore').show();}});var revealDuration=1;var revealStartTime=0.5;if($(".video-banner-caption").length){var videoCaption=gsap.timeline();videoCaption.to('.video-banner-caption-text',revealDuration,{autoAlpha:1},revealStartTime).pause();videoCaption.play();}
if($(".intro-section-slants").length){var introSlant=gsap.timeline({paused:true});if($('.intro-section-slants .left-slant').length){introSlant.to('.intro-section-slants .left-slant',9,{yPercent:-100});}
if($('.intro-section-slants .right-slant').length){introSlant.to('.intro-section-slants .right-slant',7,{yPercent:-100},0);}}
if($(".gradient-section-slants").length){var gradientSlant=gsap.timeline({paused:true});if($('.gradient-section-slants .left-slant').length){gradientSlant.to('.gradient-section-slants .left-slant',2,{yPercent:-15});}
if($('.gradient-section-slants .right-slant').length){gradientSlant.to('.gradient-section-slants .right-slant',2,{yPercent:-15},0);}}
if($(".section-top-slant").length){var gradientTopSlant=gsap.timeline({paused:true});gradientTopSlant.fromTo('.section-top-slant',0.8,{yPercent:0},{yPercent:-100,ease:Linear.easeNone},"+=0.5");}
if($(".home-page-slants").length){var homeSlantHide=gsap.timeline({paused:true});homeSlantHide.fromTo('.home-page-slant-item',0.8,{yPercent:0},{yPercent:-1,ease:Linear.easeNone},"+=0.1");}
if($(".page-title, .section-title, .small-section-title").length){var pageTitleTL=gsap.timeline();pageTitleTL.fromTo('.page-title, .section-title, .small-section-title',revealDuration,{xPercent:0,autoAlpha:0},{xPercent:0,autoAlpha:1},revealStartTime).pause();pageTitleTL.play();}
sessionStorage.setItem("aboutHtml",$(".intro-section-txt").html());if($(".intro-section-txt").length){$('.intro-section-txt').splitLines({tag:'<div>',keepHtml:true});}
if($("[data-splitting]").length){Splitting();}
if($(".intro-section-txt").length){var introText=gsap.timeline({onComplete:function(){$(".intro-section-txt").addClass("animation-complete");}});introText.to('.intro-section-txt',0.1,{autoAlpha:1}).staggerFromTo('.intro-section-txt > div',0.3,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0,delay:0,ease:Power0.easeIn},0.1).to('.intro-section .read-more-link',0.35,{left:0,autoAlpha:1},"-=0.3").to('.intro-section .read-more-link i',0.2,{left:0,autoAlpha:1},"+=0.05").staggerTo('.highlighted-txt .char',0.02,{color:aboutHighlightTextColor,opacity:1,ease:Power1.easeIn},0.02,"+=1").pause();}
if($(".Strategy-section").length){var stretagySection=gsap.timeline();stretagySection.fromTo('.Strategy-section-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime).pause();}
if($(".gradiant-counter-content-section").length){var gradiantCounter=gsap.timeline();gradiantCounter.fromTo('.gradiant-banner-title, .counter-column-wrapper, .gradient-section-slants-content-wrap p',revealDuration,{autoAlpha:0},{autoAlpha:1},+1).pause();}
if($(".sitemap-section").length){var sitemapAnim=gsap.timeline();sitemapAnim.fromTo('.sitemap-top-wrap, .sitemap-bottom-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},+1).pause();}
if($(".our-strategies-tabs-content").length){var tab_selector,tablist,current_active,list_lenth;tab_selector=".our-strategies-section";tablist=$('.our-strategies-section .nav-tabs > li > a[data-toggle="tab"]');list_lenth=tablist.length;$(".our-strategies-section .tab_nav").click(function(e){e.preventDefault();$(tablist).each(function(index){if($(this).hasClass("active")){current_active=index;}});if($(this).hasClass("prev")){if(current_active!==0){$(tablist[current_active-1]).tab("show");}else{$(tablist[list_lenth-1]).tab("show");}}else if($(this).hasClass("next")){if(current_active!=list_lenth-1){$(tablist[current_active+1]).tab("show");}else{$(tablist[0]).tab("show");}}});}
if($(".approach-section-wrap").length){var strategySection=gsap.timeline();strategySection.fromTo('.approach-section-wrap .approach-intro-content',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($(".esg-block").length){var esgBlock=gsap.timeline({paused:true,onComplete:function(){$('.esg-block .esg-list').addClass('anime-completed')}});if($('.esg-block .esg-content').length){esgBlock.fromTo('.esg-block .esg-content',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.esg-block .esg-list').length){esgBlock.fromTo('.esg-block .esg-item',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime);}
var ctrlApproach=new ScrollMagic.Controller();var sceneEsgBlock=new ScrollMagic.Scene({triggerElement:".approach-section-wrap",reverse:false}).setTween(esgBlock.play()).addTo(ctrlApproach);if(window.matchMedia("(min-height: 768px)").matches){sceneEsgBlock.triggerHook(0.6);}else{sceneEsgBlock.triggerHook(0.5);}}
if($('.about-section').length){var aboutSection=gsap.timeline();aboutSection.fromTo('.about-sub-section, .about-spotlight-section, .year-review-section, .impact-themes-section',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime).pause();var ctrlAbout=new ScrollMagic.Controller();var sceneAbout=new ScrollMagic.Scene({triggerElement:".about-sub-section, .about-spotlight-section, .year-review-section, .impact-themes-section",reverse:false}).setTween(aboutSection.play()).addTo(ctrlAbout);}
if($('.ip-slider').length){var ctrlIpSlider=new ScrollMagic.Controller();var tlIpSliderContent=gsap.timeline({paused:true});tlIpSliderContent.fromTo('.ip-header',0.5,{autoAlpha:0},{autoAlpha:1}).fromTo('.ip-slider .carousel-control',0.5,{autoAlpha:0},{autoAlpha:1});new ScrollMagic.Scene({triggerElement:".ip-slider",triggerHook:0.65,reverse:false}).setTween(tlIpSliderContent.play()).addTo(ctrlIpSlider);}
var tlIpSliderLoad=gsap.timeline({paused:true});var tlIpSliderChange;slides=$('.ip-slider .ip-item').toArray();var baseTime=0.12;var titleYPercent=115;function initIpSlider(){if($('.ip-slider').length){resetIpSlider();if(window.matchMedia("(min-width: 1200px)").matches){titleYPercent=115;}else{titleYPercent=140;}
var splitWidth=$('.ip-slider .ip-item.active .split-lines').outerWidth();if($(".ip-item-content").length){$('.investment-block .ip-item').each(function(index,item){$splitLine=$(item).find('.ip-item-content .split-lines');$heading=$(item).find('.ip-item-title .heading');$splitLine.attr('data-text',$splitLine.text());$heading.attr('data-text',$heading.text());$splitLine.splitLines({tag:'<div class="splitted"><span>',keepHtml:true,width:splitWidth});$heading.wrapInner('<span></span>');});}
$('.ip-slider .ip-item').addClass('carousel-item');tlIpSliderLoad.staggerFromTo('.ip-slider .ip-item.active .heading span, .ip-slider .ip-item.active .splitted span',baseTime*7.5,{autoAlpha:0,yPercent:titleYPercent},{autoAlpha:1,yPercent:0,ease:Power4.easeOut},baseTime);var sceneIpSlider=new ScrollMagic.Scene({triggerElement:".ip-slider",triggerHook:0.65,reverse:false}).setTween(tlIpSliderLoad.play()).addTo(ctrlIpSlider);tlIpSliderChange=new TimelineMax({paused:true});$(".ip-slider").on("slid.bs.carousel",function(event){handleIpSlideChange(event);});$('.ip-slider').carousel({pause:false,ride:true,interval:8000});$('.ip-slider').addClass('slider-initiated');setTimeout(function(){$('.ip-slider').removeClass('resizing');},800);}}
function resetIpSlider(){if($('.ip-slider').length){if($('.ip-slider').hasClass('slider-initiated')){$('.ip-slider').carousel('dispose').removeClass('slider-initiated');$('.ip-slider .ip-item').removeClass('carousel-item');tlIpSliderChange.kill();$('.investment-block .ip-item').each(function(index,item){$splitLine=$(item).find('.ip-item-content .split-lines');$splitLine.html($splitLine.attr('data-text'));$heading=$(item).find('.ip-item-title .heading');$heading.html($heading.attr('data-text'));});if(window.matchMedia("(min-width: 768px)").matches){titleYPercent=110;}else{titleYPercent=125;}}}}
initIpSlider();var loop;$(window).on('resize',function(){$('.ip-slider').addClass('resizing');clearTimeout(loop);loop=setTimeout(doneResizing,500);});function doneResizing(){initIpSlider();}
function handleIpSlideChange(event){var slideIndex=String(event.to+1).padStart(2,'0');$('.ip-slide-index').html(slideIndex);var baseTime=0.12;tlIpSliderChange.staggerFromTo($(slides[event.from]).find('.heading span'),baseTime*7.5,{yPercent:0},{yPercent:-titleYPercent,ease:Power4.easeOut},baseTime).addLabel("titleOutAnimeDone").staggerFromTo($(slides[event.from]).find('.splitted span'),baseTime*7.5,{autoAlpha:1,yPercent:0},{autoAlpha:0,yPercent:-100,ease:Power4.easeIn},baseTime,"titleOutAnimeDone-="+baseTime*10).addLabel("AllOutAnimeDone").staggerFromTo($(slides[event.to]).find('.splitted span'),baseTime*7.5,{autoAlpha:0,yPercent:100},{autoAlpha:1,yPercent:0,ease:Power4.easeOut},baseTime,"AllOutAnimeDone-="+baseTime*5).staggerFromTo($(slides[event.to]).find('.heading span'),baseTime*7.5,{yPercent:titleYPercent},{yPercent:0,ease:Power4.easeOut},baseTime,"AllOutAnimeDone-="+baseTime*4).play();}
if($(".guiding-principles-block").length){var guidingPronciplesSection=gsap.timeline({paused:true});if($('.guiding-principles-block .guiding-principles-note').length){guidingPronciplesSection.fromTo('.guiding-principles-block .guiding-principles-note',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime);}
if($('.guiding-principles-block .guiding-principles-icons-wrap .guiding-principles-icon-block').length){guidingPronciplesSection.fromTo('.guiding-principles-block .guiding-principles-icons-wrap .guiding-principles-icon-block',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime);}}
if($('.gradient-section-pin').length){var controller=new ScrollMagic.Controller();new ScrollMagic.Scene({triggerElement:".gradient-section-slants-content",triggerHook:1,}).setPin(".gradient-section-pin").addTo(controller);}
if($('.gradient-section-slants-content-wrap').length){var gredientSection=gsap.timeline({paused:true});gredientSection.fromTo('.gradient-section-slants-content-wrap .container > img, .gradient-section-slants-content-wrap h3',revealDuration,{autoAlpha:0},{autoAlpha:1},"+=1");}
if($(".portfolio-listing-section-wrap").length){var portfolioSection=gsap.timeline({paused:false});if($('.portfolio-caption, .portfolio-search').length){portfolioSection.fromTo('.portfolio-caption, .portfolio-search',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.portfolio-grid .grid-item').length){portfolioSection.fromTo('.portfolio-grid .grid-item',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".people-listing-section .portfolio-listing-section-wrap").length){var peopleSection=gsap.timeline({paused:false});if($('.people-listing .staff').length){peopleSection.fromTo('.people-listing .staff',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".news-listing-section").length){var newsSection=gsap.timeline({paused:true});if($('.news-listing-section .featured-news').length){newsSection.fromTo('.news-listing-section .featured-news',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.news-listing-wrap .news-box-wrap').length){newsSection.fromTo('.news-listing-wrap .news-box-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.news-listing-section .more-news-link').length){newsSection.fromTo('.news-listing-section .more-news-link',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".contact-section-content").length){var contactSection=gsap.timeline({paused:true,onComplete:function(){}});if($('.contact-note, .see-all-location-link').length){contactSection.fromTo('.contact-note, .see-all-location-link',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.map-svg').length){contactSection.fromTo('.map-svg',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}
if($('.map-svg-mobile').length){contactSection.fromTo('.map-svg-mobile',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".news-detail-section").length){var newsDetailSection=gsap.timeline({paused:true});if($('.news-date, .news-detail-left, .news-detail-right').length){newsDetailSection.fromTo('.news-date, .news-detail-left, .news-detail-right',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($(".portfolio-detail-section, .people-detail-section").length){var portfolioDetailSection=gsap.timeline({paused:true});if($('.portfolio-detail-content > .row > .detail-content-left, .portfolio-detail-content > .row > .detail-content-right, .portfolio-video-wrap').length){portfolioDetailSection.fromTo('.portfolio-detail-content > .row > .detail-content-left, .portfolio-detail-content > .row > .detail-content-right, .portfolio-video-wrap',revealDuration,{autoAlpha:0},{autoAlpha:1},revealStartTime)}}
if($('.more-menu-section').length){var moremenuContent=gsap.timeline();moremenuContent.add("start-point",0).fromTo('.more-menu-section > .container > .row > .col-md-8 > .row > .col-sm-6:first-child > .menu-widget .widget-title',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0},"start-point").staggerFromTo('.more-menu-section .menu-widget .about-menu li',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0},0.05).fromTo('.more-menu-section > .container > .row > .col-md-8 > .row > .col-sm-6:nth-child(2) > .menu-widget .widget-title',0.05,{autoAlpha:0,xPercent:100},{autoAlpha:1,xPercent:0}).fromTo('.more-menu-section .more-menu-search-background',0.2,{height:0},{height:'100%',ease:Linear.easeIn},"start-point").fromTo('.more-menu-section .search-widget .widget-title .widget-title-txt',0.2,{autoAlpha:0,xPercent:-100},{autoAlpha:1,xPercent:0,ease:Linear.easeInOut}).fromTo('.more-menu-section #typedtext',0.0001,{autoAlpha:0},{autoAlpha:1}).staggerFromTo('.more-menu-section .typedtext-all .char, .more-menu-section .typedtext-all .whitespace',0.02,{opacity:0},{opacity:1,ease:Power1.easeIn},0.02).fromTo('.more-menu-section .search-widget .underscore',1,{autoAlpha:0},{autoAlpha:1,delay:0.3,ease:Linear.easeInOut}).add("end",1).fromTo('.more-menu-section .copyright-txt',0.1,{autoAlpha:0},{autoAlpha:1},"end").fromTo('.more-menu-section .copyright-menu',0.1,{autoAlpha:0},{autoAlpha:1},"end").fromTo('.more-menu-section .more-menu-sidebar .investor-login-widget',0.1,{autoAlpha:0},{autoAlpha:1},"end").pause();moremenuContent.play();}
if($('.about-page-content-link').length){$('.about-page-content-link').on('click',function(){$.fn.fullpage.reBuild();$.fn.fullpage.moveSlideRight();return false;});}
if(document.querySelector('#fullpage')){$('#fullpage').fullpage({licenseKey:'A2B14386-2C614A99-B097591D-BAD19F4B',lockAnchors:true,anchors:['page1','page2','page3','page4'],parallaxKey:'QU5ZXzhZSWNHRnlZV3hzWVhnPWhuWQ==',parallax:true,parallaxOptions:{type:'reveal',percentage:100,property:'translate'},scrollingSpeed:1000,verticalCentered:false,fitToSectionDelay:0,controlArrows:false,scrollOverflow:true,scrollOverflowOptions:{keyBindings:{pageUp:33,pageDown:34,probeType:3}},normalScrollElements:'.dropdown-menu',onLeave:function(origin,destination,direction){onFpChange(destination);const activeSlide=origin.item.querySelector('.slide.active');var scroll=null;if(activeSlide){scroll=activeSlide.querySelector('.fp-scrollable');}else{scroll=origin.item.querySelector('.fp-scrollable');}
if(scroll){const cannotPrev=origin.index>destination.index&&scroll.fp_iscrollInstance.y<0;const cannotNext=origin.index<destination.index&&scroll.fp_iscrollInstance.y>scroll.fp_iscrollInstance.maxScrollY;if(cannotPrev||cannotNext){return false;}}
if($('.move-prev-page-sec').length){if(destination.index>1){if($(".intro-section-slants").length){introSlant.play();}
if($(".gradient-section-slants").length){gradientSlant.play();}
if($(".should-stickey").length){$('.site-header').addClass('scrolled');}}else{if($(".should-stickey").length){$('.site-header').removeClass('scrolled');}}}else{if(destination.index>0){if($(".intro-section-slants").length){introSlant.play();}
if($(".gradient-section-slants").length){gradientSlant.play();}
if($(".should-stickey").length){$('.site-header').addClass('scrolled');}}else{if($(".should-stickey").length){$('.site-header').removeClass('scrolled');}}}
if($('.move-prev-page-sec').length){if(destination.index>2){if($(".intro-section-slants").length){if(introSlant.isActive()){introSlant.progress(1);}}
if($(".gradient-section-slants").length){if(gradientSlant.isActive()){gradientSlant.progress(1);}}}}else{if(destination.index>1){if($(".intro-section-slants").length){if(introSlant.isActive()){introSlant.progress(1);}}
if($(".gradient-section-slants").length){if(gradientSlant.isActive()){gradientSlant.progress(1);}}}}
if($(destination.item).hasClass('banner-section')){if($(".video-banner-caption").length){videoCaption.play();}}else{if($(".video-banner-caption").length){}}
if($(destination.item).hasClass('intro-section')){if($(".intro-section-txt").length){setTimeout(function(){introText.play();},1000);}}
if($(destination.item).hasClass('approach-section')){if($(".approach-section-wrap").length){strategySection.play();}
if($(".guiding-principles-block").length){strategySection.eventCallback("onComplete",function(){guidingPronciplesSection.play(0);});}}
if($(destination.item).hasClass('gradient-section-slants-content')){aboveSection=$(origin.item).attr("data-anchor");if($(".section-top-slant").length){gradientTopSlant.play();}
if($(".gradient-section-slants-content-wrap").length){gredientSection.play();}}else if($(destination.item).attr("data-anchor")==aboveSection){if($(".gradient-section-slants-content-wrap").length){gredientSection.progress(0.8);gredientSection.reverse();}
if($(".section-top-slant").length){gradientTopSlant.reverse(0.8);}}
if($(destination.item).hasClass('gradiant-counter-content-section')){aboveSection=$(origin.item).attr("data-anchor");if($(".gradiant-counter-content-section").length){countNumber();gradiantCounter.play();}}
else if($(destination.item).attr("data-anchor")==aboveSection){if($(".gradiant-counter-content-section").length){gradiantCounter.progress(1);gradiantCounter.reverse(0.1);}}
if($(destination.item).hasClass('intro-section')){aboveSection=$(origin.item).attr("data-anchor");if($(".home-page-slants").length){homeSlantHide.play();}}else if($(destination.item).hasClass("banner-section")){if($(".home-page-slants").length){homeSlantHide.reverse(0.8);}}
if($(destination.item).hasClass('move-next-page-sec')){if($(".move-next-page-sec").length){gsap.delayedCall(0,moveToNextPageOnSroll);}}
if($(destination.item).hasClass('Strategy-section')){if($(".Strategy-section").length){stretagySection.play();}}
if($(destination.item).hasClass('portfolio-listing-section')){if($(".portfolio-listing-section-wrap").length){portfolioSection.play();}}
if($(destination.item).hasClass('sitemap-section')){if($(".sitemap-section").length){sitemapAnim.play();}}
if($(destination.item).hasClass('people-listing-section')){if($(".people-listing-section .portfolio-listing-section-wrap").length){peopleSection.play();}}
if($(destination.item).hasClass('news-listing-section')){if($(".news-listing-section").length){newsSection.play();}}
if($(destination.item).hasClass('contact-section')){if($(".contact-section-content").length){contactSection.play();}}
if($(destination.item).hasClass('news-detail-section')){if($(".news-detail-section").length){newsDetailSection.play();}}
if($(destination.item).hasClass('portfolio-detail-section')){if($(".portfolio-detail-section").length){portfolioDetailSection.play();}}
if($(destination.item).hasClass('people-detail-section')){if($(".people-detail-section").length){portfolioDetailSection.play();}}
if($('.move-prev-page-sec').length){if(destination.index==0&&direction=='up'){moveToPrevPageOnSroll();}
if(destination.index==1&&direction=='up'){if($(".intro-section-slants").length){introSlant.reverse(1);}
if($(".gradient-section-slants").length){gradientSlant.reverse(1);}}}else{if(destination.index==0&&direction=='up'){if($(".intro-section-slants").length){introSlant.reverse(1);}
if($(".gradient-section-slants").length){gradientSlant.reverse(1);}}}},afterLoad:function(origin,destination,direction){if(!$('html').hasClass('fullpage-ready')){$('html').addClass('fullpage-ready');}
if($(destination.item).hasClass('intro-section')){if($(".intro-section-txt").length){introText.play();}}
if($(destination.item).hasClass('about-section')){if($(".about-section").length){}}
if($('.scroll-up-sec').length){if(destination.index==0){$.fn.fullpage.silentMoveTo('page3',0);}}
if($(destination.item).hasClass('approach-section')){if($(".approach-section-wrap").length){strategySection.play();}
if($(".guiding-principles-block").length){strategySection.eventCallback("onComplete",function(){guidingPronciplesSection.play(0);});}}
if($(destination.item).hasClass('portfolio-listing-section')){if($(".portfolio-listing-section-wrap").length){portfolioSection.play();}}
if($(destination.item).hasClass('people-listing-section')){if($(".people-listing-section .portfolio-listing-section-wrap").length){peopleSection.play();}}
if($(destination.item).hasClass('news-listing-section')){if($(".news-listing-section").length){newsSection.play();}}
if($(destination.item).hasClass('contact-section')){if($(".contact-section-content").length){contactSection.play();}}
if($(destination.item).hasClass('news-detail-section')){if($(".news-detail-section").length){newsDetailSection.play();}}
if($(destination.item).hasClass('portfolio-detail-section')){if($(".portfolio-detail-section").length){setTimeout(function(){$.fn.fullpage.reBuild();},300);}}
if($(destination.item).hasClass('portfolio-detail-banner')){if($(".portfolio-detail-section").length){setTimeout(function(){$.fn.fullpage.reBuild();},100);}}
if($(destination.item).hasClass('people-detail-section')){if($(".people-detail-section").length){portfolioDetailSection.play();}}},onSlideLeave:function(section,origin,destination,direction){},afterRender:function(){}});}
setTimeout(function(){$.fn.fullpage.reBuild();},1000);if($('.people-listing-section').length){$('.people-listing').isotope({});}
if($('.switch-view').length){$('.switch-view a').click(function(e){e.preventDefault();$switch=$(this);var selectedView=$switch.attr('data-view');if(selectedView=='grid'){$('.people-listing').removeClass('list-view');$('.people-listing').isotope({});}else if(selectedView=='list'){$('.people-listing').addClass('list-view');$('.people-listing').isotope({});}
$('.people-listing').isotope({});$('.switch-view a').removeClass('active');$switch.addClass('active');setTimeout(function(){$.fn.fullpage.reBuild();},600);});}
if($('.portfolio-grid').length){var buttonFilters={};var buttonFilter;var qsRegex;var $portfolioGrid=$('.portfolio-grid').isotope({itemSelector:'.grid-item',masonry:{columnWidth:0,},getSortData:{alphabetical:'[data-name]',year:'[data-year] parseInt',},filter:function(){var $this=$(this);var searchResult=qsRegex?$this.attr('data-name').match(qsRegex):true;var buttonResult=buttonFilter?$this.is(buttonFilter):true;return searchResult&&buttonResult;},});$portfolioGrid.on('arrangeComplete',function(event,filteredItems){if(filteredItems.length==0){$('.no-data-div').show();}else{$('.no-data-div').hide();}
setTimeout(function(){$.fn.fullpage.reBuild();},600);});$('.filter-group').on('click','.dropdown-menu a',function(){var $this=$(this);var $buttonGroup=$this.parents('.dropdown-menu');var filterGroup=$buttonGroup.attr('data-filter-group');buttonFilters[filterGroup]=$this.attr('data-filter');buttonFilter=concatValues(buttonFilters);$portfolioGrid.isotope();setTimeout(function(){$.fn.fullpage.reBuild();},600);});var $quicksearch=$('#investmentsSearch').keyup(debounce(function(){qsRegex=new RegExp($quicksearch.val(),'gi');$portfolioGrid.isotope();}));$('#sorts').on('click','.dropdown-menu a',function(){var sortByValue=$(this).attr('data-sort-by');$('.portfolio-grid').isotope({sortBy:sortByValue});setTimeout(function(){$.fn.fullpage.reBuild();},600);});$('.dropdown-menu').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','.portfolio-sorting-wrap .dropdown-menu a, .people-filter .dropdown-menu a',function(event){$buttonGroup.find('.selected').removeClass('selected');var $button=$(event.currentTarget);$button.addClass('selected');});setTimeout(function(){$.fn.fullpage.reBuild();},600);});function concatValues(obj){var value='';for(var prop in obj){value+=obj[prop];}
return value;}
function debounce(fn,threshold){var timeout;threshold=threshold||100;return function debounced(){clearTimeout(timeout);var args=arguments;var _this=this;function delayed(){fn.apply(_this,args);}
timeout=setTimeout(delayed,threshold);};}}
if($('.people-listing').length){var buttonFilters={};var buttonFilter;var qsRegex;var $peopleGrid=$('.people-listing').isotope({itemSelector:'.people-grid',filter:function(){var $this=$(this);var $name=$(this).find('.team-desc h4 > span');var searchResult=qsRegex?$name.text().match(qsRegex):true;var buttonResult=buttonFilter?$this.is(buttonFilter):true;return searchResult&&buttonResult;},});$peopleGrid.on('arrangeComplete',function(event,filteredItems){if(filteredItems.length==0){$('.no-data-div').show();}else{$('.no-data-div').hide();}
setTimeout(function(){$.fn.fullpage.reBuild();},600);});$peopleGrid.isotope();$('.people-filter').on('click','.dropdown-menu a',function(){console.log('people');var $this=$(this);var $buttonGroup=$this.parents('.dropdown-menu');var filterGroup=$buttonGroup.attr('data-filter-group');buttonFilters[filterGroup]=$this.attr('data-filter');buttonFilter=concatValues(buttonFilters);$peopleGrid.isotope();setTimeout(function(){$.fn.fullpage.reBuild();},600);});var $quicksearch=$('#investmentsSearch').keyup(debounce(function(){qsRegex=new RegExp($quicksearch.val(),'gi');$peopleGrid.isotope();}));$('.dropdown-menu').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','.portfolio-sorting-wrap .dropdown-menu a, .people-filter .dropdown-menu a',function(event){$buttonGroup.find('.selected').removeClass('selected');var $button=$(event.currentTarget);$button.addClass('selected');});setTimeout(function(){$.fn.fullpage.reBuild();},600);});function concatValues(obj){var value='';for(var prop in obj){value+=obj[prop];}
return value;}
function debounce(fn,threshold){var timeout;threshold=threshold||100;return function debounced(){clearTimeout(timeout);var args=arguments;var _this=this;function delayed(){fn.apply(_this,args);}
timeout=setTimeout(delayed,threshold);};}
$('.dropdown-menu').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','.portfolio-sorting-wrap .dropdown-menu a, .people-filter .dropdown-menu a',function(event){$buttonGroup.find('.selected').removeClass('selected');var $button=$(event.currentTarget);$button.addClass('selected');});setTimeout(function(){$.fn.fullpage.reBuild();},600);});function concatValues(obj){var value='';for(var prop in obj){value+=obj[prop];}
return value;}}
$('.spotlight-slider').slick({nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',dots:false,infinite:false,speed:300,slidesToShow:2,centerPadding:'0px',responsive:[{breakpoint:991,settings:{slidesToShow:1,centerMode:true,}},]});if(window.matchMedia("(min-width: 768px)").matches){explandContent();}
if(window.matchMedia("(max-width: 767px)").matches){explandContentMobile();}
if(window.matchMedia("(min-width: 992px)").matches){tabExpandContent();}
if(window.matchMedia("(max-width: 991px)").matches){tabExpandContentMobile();}
if($('.news-detail-content').length){SocialURL();}
function explandContent(){$('.impact-block-wrapper .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').slideUp(300);$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').slideDown(400);$(this).parent('.expand-icon-wrap').closest('.row').find('.themes-icon-box').find('.themes-content').find('.theme-text-accordion').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
$this.addClass("active");setTimeout(function(){$.fn.fullpage.reBuild();},600);});}
function explandContentMobile(){$('.impact-block-wrapper .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').slideUp(300);$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').slideDown(300);$(this).parent('.expand-icon-wrap').parent('.themes-icon-box-wrap').find('.theme-text-accordion').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
setTimeout(function(){$.fn.fullpage.reBuild();},600);$this.addClass("active");});}
function tabExpandContent(){$('.management-boxes-wrap .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideUp(300);$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideDown(300);$(this).parent('.expand-icon-wrap').parent('.row').find('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
setTimeout(function(){$.fn.fullpage.reBuild();},600);$this.addClass("active");});}
function tabExpandContentMobile(){$('.management-boxes-wrap .expand-icon-wrap a').click(function(){$this=$(this);if($this.hasClass("expanded")){$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideUp(300);$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').removeClass('expanded');$(this).removeClass('expanded');$(this).text('Read more');}else{$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').slideDown(300);$(this).parent('.expand-icon-wrap').parent('.management-boxes-single').find('.management-boxes-content').find('.management-expand-text').addClass('expanded');$(this).addClass('expanded');$(this).text('Less');}
setTimeout(function(){$.fn.fullpage.reBuild();},600);$this.addClass("active");});}
function countNumber(){setTimeout(function(){$('.count-no .anim').each(function(){var $this=$(this);jQuery({Counter:0}).animate({Counter:$this.text()},{duration:1000,delay:4000,easing:'swing',step:function(){$this.text(Math.ceil(this.Counter));}});});},1200)};function fpGenerate(){if($(".fp-fixed").length){$fpFixed=$(".fp-fixed");fpCount=$("#fullpage .section").length;$fpFixed.html("");$("#fullpage .section").each(function(i,e){var fpGroup=$(e).attr("data-fp-group");if(typeof fpGroup==="undefined"){fpGroup="";}else{fpGroup="group-"+$(e).attr("data-fp-group");}
if($("."+fpGroup).length==0){$fpFixed.append('<div class="fp-group-section '+fpGroup+'"></div>');}
var fpStyles=$(e).attr("data-fp-style");if(typeof fpStyles==="undefined"){fpStyles="";}
$("."+fpGroup).append("<div class='fp-synced-section' style='"+fpStyles+"'></div>");var fpInr="";if(typeof $(e).find(".fp-fixed-inr")[0]!=="undefined"){fpInr=$(e).find(".fp-fixed-inr")[0].innerHTML;}
$("."+fpGroup).append(fpInr);});$fpFixed.find(".fp-group-section:first-of-type").addClass("active").find(".fp-synced-section:first-of-type").addClass("active");}}
function onFpChange(destination){var fpGroup=$(destination.item).attr("data-fp-group");var $fpGroupAll=$(".fp-fixed .fp-group-section");$fpGroupAll.removeClass("active");$thisGroup=$(".fp-fixed .group-"+fpGroup);$thisGroup.addClass("active");var $fpBgAll=$(".fp-fixed .fp-synced-section");$fpBgAll.removeClass("active");$($fpBgAll[destination.index]).addClass("active");var activeIndex=$thisGroup.find(".fp-synced-section").index($(".fp-synced-section.active"));if(activeIndex>0){$thisGroup.find(".fp-fixed-content").addClass("non-first");}else{$thisGroup.find(".fp-fixed-content").removeClass("non-first");}}
if($('.strategies-tab-section').length){accordionRebuilt();accordionScrolling();}
function accordionRebuilt(){$('#stratagyAccrodion').on('shown.bs.collapse',function(){$.fn.fullpage.reBuild();});$('#stratagyAccrodion').on('hidden.bs.collapse',function(){$.fn.fullpage.reBuild();});}
function accordionScrolling(){$(".strategies-tabs-content .card-header button").click(function(){const scrollable=$('.fp-section.active').find('.fp-scrollable')[0];if(scrollable&&typeof scrollable!==undefined){const scrollInstance=scrollable.fp_iscrollInstance;const scrollSection=$('.Strategy-intro').height();console.log(scrollSection);scrollInstance.scrollTo(0,-scrollSection,1000);setTimeout(function(){scrollInstance.refresh();},1000+150);}})}
function SocialURL(){$(".sharePage ul li a").click(function(){var urlPath=window.location.href;if($(this).hasClass('addthis_button_email')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/email/offer?url="+urlPath);}else if($(this).hasClass('addthis_button_linkedin')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/linkedin/offer?url="+urlPath);}else if($(this).hasClass('addthis_button_twitter')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url="+urlPath);}else if($(this).hasClass('addthis_button_facebook')){$(this).attr("href","https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url="+urlPath);}});}
$('.strategies-tabs .nav-link').click(function(){setTimeout(function(){$.fn.fullpage.reBuild();},600);});$('.portfolio-sorting-wrap .dropdown-menu a, .people-listing-section .dropdown-menu a').click(function(){console.log('click');$('.portfolio-sorting-wrap .dropdown-menu a, .people-listing-section .dropdown-menu a').removeClass('selected');$(this).addClass('selected');$(this).closest('.dropdown-menu').closest('.dropdown').find(".psorting").find('.selected-value').text($(this).text());});stickySidebar();setTimeout(function(){$('.more-menu-link.backLink').addClass('open');},10);$('.more-menu-link.backLink').on('click',function(){window.history.go(-1);changePageSlantColor();$(this).removeClass('open');return false;});$('.more-menu-section ul li a').on('click',function(){$('.more-menu-link').removeClass('open');});$('.navbar-brand').on('click',function(){console.log("Clicked");$('.more-menu-link').removeClass('open');});$('.scroll-down-link').on('click',function(e){e.preventDefault();fullpage_api.moveSectionDown();});$('.dropdown').on('shown.bs.dropdown',function(e){setTimeout(function(){$(e.target).addClass('shown');},350);});$('.dropdown').on('hide.bs.dropdown',function(e){$(e.target).removeClass('shown');});}
function unload(){if(document.querySelector('#fullpage')){$.fn.fullpage.destroy('all');}}
function moremenuSidebarBgPlacement(){if($('.more-menu-sidebar').length){var moremenuSidebar=$(".more-menu-section .more-menu-sidebar");var moremenuSidebarBg=$(".more-menu-section .more-menu-search-background");var moremenuSidebarOffsetLeft=$(moremenuSidebar).offset().left;$(moremenuSidebarBg).css('left',moremenuSidebarOffsetLeft);}}
function stickySidebar(){if($(".sideStick").length&&window.matchMedia("(min-width: 768px)").matches){if($('body').find('.matchWrap').length){$(".sideStick").stick_in_parent({parent:'.matchWrap',offset_top:100});var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});var windowWidth=$(window).width();$(window).resize(function(){var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();if($(window).width()!=windowWidth){$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});}});}else{$(".sideStick").stick_in_parent({parent:'.news-detail-content',offset_top:100,spacer:false,});var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});var windowWidth=$(window).width();$(window).resize(function(){var widthN=$('.sideStick').parent('.sidestickParentW').innerWidth();if($(window).width()!=windowWidth){$('.sideStick').on('sticky_kit:bottom',function(){$(this).parent().css('position','static');$(this).css('width',widthN+'px');}).on('sticky_kit:unbottom',function(){$(this).parent().css('position','relative');});}});}}}
function moveToNextPageOnSroll(){changePageSlantColor();var currentPage;if(document.location.pathname=="/"){currentPage='/';}else{currentPage=document.location.pathname.match(/[^\/]+$/);}
if(currentPage=='/'){swup.loadPage({url:'/about-us',});}else{if($(".bottom-header .navbar-nav > li.active").length){if(!$(".bottom-header .navbar-nav > li.active").is(':last-child')){navNextLink=$(".bottom-header .navbar-nav > li.active a").parent().next().children("a").attr("href");swup.loadPage({url:navNextLink,});}}}}
function moveToPrevPageOnSroll(){changePageSlantColor();var currentPage=document.location.pathname.match(/[^\/]+$/);if(currentPage=='about-us'){swup.loadPage({url:'/',});}else{if($(".bottom-header .navbar-nav > li.active").length){navNextLink=$(".bottom-header .navbar-nav > li.active a").parent().prev().children("a").attr("href");swup.loadPage({url:navNextLink,});}}}
function setVideoHeight(){setTimeout(function(){var windowHgt=$('html').height();$('.video-banner .embed-responsive').css('max-height',windowHgt);},1000);}
function splitLinesAnimation(className,isChange=false){if(sessionStorage.getItem('thisPage')=='index'){if(isChange){$(className).html(sessionStorage.getItem("aboutHtml"));}
if($(className).length){$(className).splitLines({tag:'<div>',keepHtml:true});}
if($("[data-splitting]").length){Splitting();}
$(".intro-section-txt.animation-complete .highlighted-txt .char").css("color",aboutHighlightTextColor);}}
(()=>{let headerTitle=document.querySelector('.header-subbar__title'),headerSubbarMenu=document.querySelector('.header-subbar-menu'),spans=document.querySelectorAll('.header-subbar-menu span'),navBarEnabled=0,doubleLinksCont=document.querySelectorAll('.nav-bar__link-cont'),links=document.querySelectorAll('.nav-bar__link:not(.nav-bar__link-sub)')
headerTitle.onclick=()=>window.location='../../'
links.forEach((i)=>{if(i.href===window.location.href){i.style.color='hsl(235, 51%, 37%)'
i.style.cursor='default'
i.style.textDecoration='underline'
i.addEventListener('click',(e)=>{e.preventDefault()})}})
let t1=gsap.timeline({paused:true})
t1.to([spans[0],spans[1]],{opacity:0,y:'50%',duration:.2})
t1.to(spans[2],{rotateZ:'45deg',duration:.2})
t1.to(spans[3],{rotateZ:'-45deg',duration:.2},'<')
t1.to('.nav-bar',{x:'-100%',duration:.4,ease:'Power1.out'},'<')
t1.to('.nav-bar__link',{opacity:1,duration:.2,ease:'Power1.out'})
t1.to('.nav-bar__arrow',{opacity:1,duration:.2,ease:'Power1.out'},'<')
headerSubbarMenu.addEventListener('click',()=>{!navBarEnabled?t1.play().then(()=>navBarEnabled=1):t1.reverse().then(()=>navBarEnabled=0)})
doubleLinksCont.forEach((item,id)=>{let doubleLinks=item.querySelectorAll('a'),arrow=item.querySelectorAll('.nav-bar__arrow'),active=0
let t2=gsap.timeline({paused:true})
for(let link of doubleLinks){t2.to(link,{y:0,height:window.innerWidth>1024?'50px':'30px',lineHeight:window.innerWidth>1024?'50px':'30px',duration:.2},'<')
t2.to(link,{zIndex:1,color:'hsl(235, 51%, 32%)',duration:.2},.1)}
t2.to(arrow,{rotateZ:540,duration:.4})
item.addEventListener('click',()=>{!active?t2.play().then(()=>active=1):t2.reverse().then(()=>active=0)})
window.addEventListener('click',e=>{let navBarWidth=window.innerWidth>1024?window.innerWidth/2:window.innerWidth/4
navBarEnabled&&e.pageX<navBarWidth?t1.reverse().then(()=>navBarEnabled=0):''})})})()